Castro19/LAEP-GPT

Client/package.json
Client/src/App.jsx
Client/src/components/Header.jsx
Client/src/components/ModeDropDown.jsx
Client/src/components/NewChat.jsx
Client/src/components/Sidebar.jsx
Client/src/components/chat/ChatContainer.jsx
Client/src/components/chat/ChatInput.jsx
Client/src/components/chat/ChatLog.jsx
Client/src/components/chat/ChatMessage.jsx
Client/src/components/contexts/MessageContext.jsx
Client/src/components/contexts/ModelContext.jsx
Client/src/components/contexts/UIContext.jsx
Client/src/utils/createLog.js
Client/src/utils/handleNewChat.js
server/index.js

1.) I started by first implementing the sidebar logic to store my current chat log. I created a new state variable called "logList" as an array. Each of the elements in here are objects containing a title, timestamp, and content (the msgList containing all the messages). Continuing this logic, I was able store the previous chat logs in this state variable and access different chat logs from the sidebar and continue chats where Ieft off.
Each chat log will also generate a title on the back-end automatically. Future implementations will use AI to generate the title based on the first message.
Implementing UUID, for each chat log will also be implemented.
2.) New Chats: Working along the sidebar logic, I wanted to reset the state of my msgList state variable.
3.) Context API: Implementing …

3 main Features in this pull request: SideBar Logic/New Chats/Context State Variables

---

Client/src/components/NewChat.jsx
Client/src/components/chat/ChatContainer.jsx
Client/src/utils/createLog.js
Client/tailwind.config.js

Tested multiple test cases where I created multiple chat logs, went back and forth, spammed the new chat button and the functionality still works!

Finalizing SideBar logic functionality

---

Client/src/components/chat/ChatContainer.jsx
Client/src/components/chat/ChatInput.jsx
Client/src/components/chat/ChatMessage.jsx
Client/src/components/layout/Sidebar.jsx
Client/src/index.css
Client/src/pages/ChatPage.jsx
Client/src/pages/customGPT/GPTPage.jsx
Client/src/pages/customGPT/GPTPage.module.css
README.md

Formatting issues fixed.
Chat input area now moves with the rest of the chat page when sidebar is toggled.
Scroll areas are now fixed where the overflow is only hidden on the chat page to prevent there from being two scroll bars.

Updated Chat Input text area

---

Client/src/components/chat/ChatInput.tsx
Client/src/redux/message/messageSlice.ts
Client/src/types/message/messageType.ts
server/helpers/azure/blobFunctions.js
server/package-lock.json
server/package.json
server/routes/chatLog.js
server/routes/fileOperations.js
server/routes/llm.js

- Created a Redux slice to manage PDF file state.
- Cleared the PDF file after a message is sent to avoid duplication.
- Added helper function to store files locally on the system.
- Implemented a function to upload files to OpenAI, followed by local file deletion after upload.
- Updated chatlog deletion to remove all associated files from the vector store.

Improvement: File Upload System

---

Client/src/components/register/WeeklyCalendar.tsx
Client/src/pages/register/ProfilePage.tsx
Client/src/types/auth/authTypes.ts

- Availability option is now in a JSON format stored on MongoDB
- Users can easily add time slots by dragging mouse or clicking slots
- Better structure than text

Availability Editing option

---

Client/src/components/register/InterestDropdown.tsx
Client/src/components/register/SignInFlow/AboutMe.tsx
Client/src/components/register/SignInFlow/index.tsx
Client/src/components/register/TitleCard.tsx
Client/src/components/register/WeeklyCalendar.tsx
Client/src/components/security/ProtectedRoute.tsx
Client/src/hooks/useUserData.ts
Client/src/main.tsx
Client/src/pages/register/ProfilePage.tsx
Client/src/pages/register/Register.tsx
Client/src/redux/auth/authSlice.ts
Client/src/types/auth/authTypes.ts

- New users now go through a user sign up flow where they input their information
- Custom hook to easily edit the userData 
- Components for each section of the sign-up flow can be re-used like in the ProfilePage

Sign-Up-Flow

---

Client/src/components/customGPT/GPTList/GPTList.tsx

Fixed bug by calling a useEffect that fetches the Gpts from our database.
Could be enhanced by adding a listener in gptSlice

GPT List Bug

---

.github/workflows/main_laep-llm.yml
package.json
server/package.json

- Pausing Deployment pipeline for now until we have azure setup
- Local Deployment is now using `nodemon` on the server

Workflow Modifications

---

Client/src/components/security/NewUserRoute.tsx
Client/src/hooks/useUserData.ts
Client/src/main.tsx
Client/src/pages/register/ProfilePage.tsx
Client/src/redux/auth/crudAuth.ts

- **Infinite Redirects**: The component for `ProtectedRoute` was causing an infinite redirect and not handling the sign-in flow content correctly
- Check the current location in the `ProtectedRoute` to avoid redirecting users who are already on the sign-in flow route.
- Create a new `NewUserRoute` component that would ensure only new users can access the sign-in flow route.

[Bug-Fix] Added new Protected Route for new Users

---

Client/src/components/chat/ChatInput.tsx
Client/src/components/customGPT/ModeDropDown.tsx
Client/src/components/layout/Header.tsx
Client/src/redux/message/crudMessage.ts
Client/src/types/gpt/gptTypes.ts
server/db/models/analytics/messageAnalytics/messageAnalyticsCollection.js
server/db/models/gpt/gptCollection.js
server/helpers/formatters/availabilityFormatter.js
server/helpers/openAI/threadFunctions.js
server/index.js
server/routes/llm.js

- Uploaded a json file to the matching assistant on openAI website
- File contains a list of all the teachers in the CS department along with their availability, interests, e-mail, etc.
- This assistant should not receive any files to upload 
- This is to make the assistant only use `file-search` for the teacher JSON file

[Feature] Assistant-Matching Student-->Teacher 

---

Client/package-lock.json
Client/package.json
Client/src/components/chat/ChatInput.tsx
Client/src/components/customGPT/ModeDropDown.tsx
Client/src/components/layout/Header.tsx
Client/src/components/ui/navigation-menu.tsx
Client/src/components/ui/toast.tsx
Client/src/main.tsx
Client/src/redux/gpt/gptSlice.ts
Client/src/redux/layout/layoutSlice.ts
Client/src/types/gpt/gptTypes.ts

- Students who have not inputted their availability or interests will not have access to the matching assistant yet.
- This is to prevent the bot from performing poorly as they have no information to match student with advisor. 
- Improved the UI of the assistant dropdown menu to allow for a cleaner appeal that suits the rest of the application.

Assistant mode dropdown

---

Client/src/components/chat/AssistantSuggestedMessages.tsx
Client/src/components/chat/ChatContainer.tsx
Client/src/components/chat/ChatInput.tsx
Client/src/components/customGPT/GPTList/GPTList.tsx
Client/src/components/customGPT/customGptCard/CustomGPTCard.tsx
Client/src/redux/gpt/gptSlice.ts
Client/src/redux/message/messageSlice.ts
Client/src/types/gpt/gptTypes.ts
Client/src/types/message/messageType.ts
server/db/models/gpt/gptServices.js
server/routes/gpt.js

- A list of buttons will appear on the screen that will be example prompts to ask the assistant
- Once the button is clicked, it dispatches the update function for the `msg` state variable. Then it uses the `sendButtonRef` to simulate the click and deliver the message to our backend.
- Everything else behaves exactly as if the user had manually typed out the message. 
- From this change, there was some issues with the auto scrolling that had to get fixed.
- For new chats, we had to make sure the messageContainer was mounted before assigning the ref and handling the scroll event listener.

Feature assistant suggested messages

---

Client/src/calpolyData/courses.json
Client/src/calpolyData/interests.json
Client/src/components/chat/AssistantSuggestedMessages.tsx
Client/src/components/chat/ChatInput.tsx
Client/src/components/customGPT/ModeDropDown.tsx
Client/src/components/layout/CustomModal.tsx
Client/src/components/layout/Header.tsx
Client/src/components/register/SignInFlow/InterestDropdown.tsx
Client/src/components/register/SignInFlow/index.tsx
Client/src/components/ui/animated-modal.tsx
Client/src/components/userProfile/Interest.tsx
Client/src/hooks/useCalpolyData.ts
Client/src/hooks/useUserData.ts
Client/src/main.tsx
Client/src/pages/ProfilePage.tsx
Client/src/redux/user/userSlice.ts
Client/src/types/auth/authTypes.ts
server/routes/llm.js

- New Assistant was created that reads the JSON file that contains the information for every CSC Course 
- Users can now add courses to their profile
- Help create schedules for students based on left over classes 
- Use the CSC Course Schedule structure to determine what courses are left over

Courses Implemented

---

Client/src/redux/message/crudMessage.ts
server/helpers/openAI/costFunction.js
server/routes/llm.js

- For every message that gets sent, we will track the number of prompt tokens, output tokens, total tokens, and estimated cost based on the model used
- For now, I am not utilizing these analytics, but they will be insightful to observe at scale on what messages cost the most amount of money.

Analytics Token Tracking

---

Client/src/components/chat/ChatInput.tsx
Client/src/redux/message/crudMessage.ts
Client/src/redux/message/messageSlice.ts
server/helpers/assistants/multiAgent.js
server/helpers/assistants/singleAgent.js
server/helpers/assistants/streamResponse.js
server/index.js
server/middlewares/asyncMiddleware.js
server/routes/analytics/messageAnalytics.js
server/routes/llm.js

- Users now have the option to cancel a message that is being streamed out
- New button for when the message state is `loading`
- New button sends a request to `/llm/cancel` which will cancel the run 
- To cancel a run, we are dispatching a thunk to send a request to the server to stop streaming
- Created new end point `/llm/cancel` to handle how the server is canceling the streamed response
- Command to cancel a run: `await openai.beta.threads.runs.cancel(threadId, runId);`

Abort streamed message

---

server/routes/chatLog.js

- Chatlogs are now deleted, even if `404` error occurs
Deleting a chatlog in the app requires deleting the following
- threadId
- vectorStoreId
- All files in the vectorStoreId (if any)
- If one of the following had a `404` for some reason, the chatlog would not get deleted.
- Ideally, I believe it would be better to delete what is available for a better user experience.
- Delete what we can by adding conditional statements before we attempt to delete a value where the id is undefined.

Deleting Chatlog Error Handling

---

Client/src/App.tsx
Client/src/components/chat/ChatInput.tsx
Client/src/components/chatLog/ChatLog.tsx
Client/src/components/layout/sidebar/Sidebar.tsx
Client/src/pages/ChatPage.tsx
Client/src/redux/log/crudLog.ts
Client/src/redux/log/logSlice.ts
server/db/models/chatlog/chatLogCollection.js
server/db/models/chatlog/chatLogServices.js
server/db/models/threads/threadCollection.js
server/db/models/threads/threadServices.js
server/helpers/assistants/multiAgent.js
server/helpers/assistants/singleAgent.js
server/helpers/openAI/threadFunctions.js
server/routes/chatLog.js
server/routes/llm.js
server/sentry/instrument.js

- Fetching the content of each chatLog when we need it 
- Fetching every chatLog with the entire content in a single request and storing it in state is not ideal
- When sending the response for the `logList` we are not sending back the `content` which is the array of messages 
- Modified some code to make it cleaner and more optimized
-

Chat log approach

---

Client/src/components/register/SignInFlow/InterestDropdown.tsx
Client/src/hooks/useUserData.ts
Client/src/redux/gpt/gptSlice.ts
Client/src/redux/message/crudMessage.ts
server/helpers/assistants/singleAgent.js
server/routes/llm.js

- Small changes to fix some bugs

Minor Changes

---

Client/src/components/customGPT/ModeDropDown.tsx
Client/src/components/flowchart/flowchartSidebar/SidebarFlowchart.tsx
Client/src/components/register/SignInFlow/FlowChartOptions.tsx
Client/src/components/register/SignInFlow/index.tsx
Client/src/pages/ProfilePage.tsx
Client/src/redux/flowSelection/flowSelectionSlice.ts
Client/src/redux/flowchart/flowchartSlice.ts
Client/src/redux/index.ts
Client/src/redux/store.ts

- New slice to separate logic between selection options for choosing a flowchart and flowchart data properties

Refactoring Flowchart Slice

---

Client/src/components/flowchart/flowchartFooter/FlowChartFooter.tsx
Client/src/components/flowchart/flowchartLog/FlowchartLog.tsx
Client/src/components/flowchart/flowchartLog/FlowchartLogOptions.tsx
Client/src/redux/flowchart/crudFlowchart.ts
Client/src/redux/flowchart/flowchartSlice.ts
Client/src/types/flowChart/flowChartTypes.ts
server/db/models/flowchart/flowchartServices.js
server/routes/flowchart.js

Creating a current flowchart Id in the slice

Flowchart refactoring

---

Client/src/components/flowchart/FlowChart.tsx
Client/src/components/flowchart/termContainer/TermContainer.tsx
Client/src/components/ui/card.tsx
Client/src/pages/ProfilePage.tsx

Fixed CSS Style colors
Years on Term Container now showing accurate term year

TermContainer Years

---

.gitignore
Client/src/components/flowchart/flowchartFooter/FlowChartFooter.tsx
Client/src/components/flowchart/flowchartLog/FlowchartLog.tsx
Client/src/components/layout/DragDropContxtWrapper.tsx
Client/src/components/layout/ProfilePage.tsx/ProfilePageLayout.tsx
Client/src/components/layout/flowchart/FlowchartLayout.tsx
Client/src/pages/ProfilePage.tsx
Client/src/redux/flowchart/crudFlowchart.ts
Client/src/redux/flowchart/flowchartSlice.ts
server/db/models/flowchart/flowchartServices.js
server/routes/flowchart.js

- 3 main changes that could have been 3 pull requests
1. DragDrop Context Layout to wrap pages that would need Drag Drop Functionality 
2. Updating Primary Flowchart
3. Deleting Primary Flowchart

DragDrop Context & Handling Updating/Deleting Flowcharts 

---

Client/src/components/flowchart/flowchartLog/FlowchartLog.tsx
Client/src/components/flowchart/flowchartLog/FlowchartLogOptions.tsx
Client/src/components/flowchart/flowchartSidebar/FlowchartSidebar.tsx
Client/src/components/flowchart/flowchartSidebar/SidebarFlowchart.tsx
Client/src/pages/FlowChatPage.tsx
Client/src/pages/ProfilePage.tsx
Client/src/redux/flowchart/flowchartSlice.ts
server/db/models/flowchart/flowchartCollection.js
server/db/models/flowchart/flowchartServices.js

- Fixed most common bugs for flowchart integration

Fixing Bugs For Flowchart

---

Client/src/components/flowchart/FlowChart.tsx
Client/src/components/flowchart/courseItem/CourseItem.tsx
Client/src/components/ui/specialButton.tsx
Client/src/pages/ProfilePage.tsx

Improved styles for course tool tip

Course ToolTIp Styles 

---

Client/package-lock.json
Client/package.json
Client/src/components/chat/ChatContainer.tsx
Client/src/components/chat/ChatInput.tsx
Client/src/components/chatLog/ChatLog.tsx
Client/src/components/chatLog/ChatLogOptions.tsx
Client/src/components/chatLog/ChatSidebarFooter.tsx
Client/src/components/flowchart/FlowChart.tsx
Client/src/components/flowchart/courseItem/CourseItem.tsx
Client/src/components/flowchart/flowchartHeader/FlowChartHeader.tsx
Client/src/components/flowchart/flowchartLog/FlowchartLog.tsx
Client/src/components/flowchart/flowchartLog/FlowchartLogOptions.tsx
Client/src/components/flowchart/flowchartSidebar/SidebarFlowchart.tsx
Client/src/components/flowchart/termContainer/TermContainer.tsx
Client/src/components/layout/ChatPage/ChatPageHeader.tsx
Client/src/components/layout/ChatPage/ChatPageSidebar.tsx
Client/src/components/layout/ProfilePage/ProfilePageHeader.tsx
Client/src/components/ui/scroll-area.tsx

- New scroll area component 
- New CSS changes

Scroll area

---

Client/src/components/chatLog/ChatLogOptions.tsx
Client/src/components/flowchart/flowchartLog/FlowchartLog.tsx
Client/src/components/flowchart/flowchartSidebar/SidebarFlowchart.tsx
Client/src/components/layout/ProfilePage/ProfilePageHeader.tsx

Sidebar improvements

---

Client/src/components/flowchart/courseItem/CourseItem.tsx
Client/src/components/flowchart/termContainer/TermContainer.tsx

- ToolTip Provider is now outside Draggable Context
- This is to allow selection of the tooltip content if the user chooses to do so

Flowchart Tooltip Trigger

---

server/db/models/courses/courseCollection.js
server/db/models/courses/courseServices.js
server/helpers/assistants/singleAgent.js
server/helpers/qdrant/qdrantQuery.js
server/index.js
server/package-lock.json
server/package.json
server/routes/courses.js

- Two new Calpoly Assistants were added in today
1. **Course Catalog**: Searches through 4000+ courses from the catalog querying from the vector database in Qdrant to find the most relevant courses 
2. **Calpoly Clubs**: Searches through 400+ clubs based on the user's major, interests, and message to provide a list of clubs the user might be interested in
- For large datasets such as the course catalog that contains 4000+ courses, we were not able to naively insert our JSON formatted data into OpenAI and allow them to do all of the work.
- This would not provided the best results, take up a lot of tokens ($), perform poorly, and overall not be a good approach
- The solution was to implement a vector database that would contain our large datasets
- By using Qdrant and OpenAI's feature of …

Calpoly Assistants 

---

Client/src/components/chat/ChatInput.tsx
Client/src/redux/message/crudMessage.ts
Client/src/redux/message/messageSlice.ts

Error Handling for Failed Messages

---

Client/src/pages/ChatPage.tsx
Client/src/redux/assistant/assistantSlice.ts
Client/src/redux/log/crudLog.ts
Client/src/redux/message/crudMessage.ts
Client/src/redux/message/messageSlice.ts
shared/src/types/assistant/index.ts
shared/src/types/message/index.ts

- Loading in initial assistant from DB
- This also allows us to hide the mongoDB id from being displayed in the code
- Deleted type as it was a duplicate of the AssistantType

Initial Assistant Loaded in

---

server/src/db/models/flowInfo/flowInfoServices.ts
server/src/db/models/flowchart/flowchartCollection.ts
server/src/db/models/flowchart/flowchartServices.ts

- FetchAll Flowcharts was console error a message when it should have not 
- Flowchart is automatically assigned a name when it is created

Bug fix fetch all flowcharts

---

server/src/db/models/professorRatings/professorRatingUtil.ts

Professor Reviews limited to the top 5 professors for each course

Professor Reviews limited

---

Client/src/components/chat/ChatMessage.tsx
Client/src/components/chat/ModeDropDown.tsx
Client/src/components/chatLog/ChatLog.tsx
Client/src/components/chatLog/ChatLogOptions.tsx

- ChatLog improvements when hovering
- ModeDropdown for small devices

More CSS Improvements

---

Client/src/components/flowchart/FlowChart.tsx
Client/src/components/flowchart/flowchartFooter/FlowChartFooter.tsx
Client/src/components/flowchart/flowchartHeader/FlowChartHeader.tsx
Client/src/components/flowchart/flowchartSidebar/SidebarFlowchart.tsx
Client/src/components/register/SignInFlow/index.tsx
Client/src/components/ui/specialButton.tsx
server/src/db/models/assistant/assistantCollection.ts
server/src/routes/llm.ts

- Hiding Matching Student to Advior assistant for now because it only contains professors in the CS department
- Hiding Flowchart assistant for now as it needs to upgrade to be a multi model agent to answer queries successfully
- Sign Up Flow removes the section on availability
- There is no assistant that is currently using this anymore so we are hiding it for now
- Moved Save and Update Button the header on the flowchart page to remain always in view
- On mobile devices I move these buttons the the footer.

Sign Up Flow & Flowchart Save

---

Client/src/components/security/ProtectedRoute.tsx
Client/src/redux/message/crudMessage.ts
Client/src/redux/message/messageSlice.ts
server/src/routes/llm.ts

- Handling LLM respond erros gracefully 
- Giving a descriptive message if the error is a rate limit or internet connection issue
- Will expand on this in the future

Rate Limit Error Handling Improvement

---

Client/src/App.tsx
Client/src/components/layout/splashPage/SplashHeader.tsx
Client/src/pages/ComingSoonPage.tsx

- Modify Splash Page Header
- Dynamic sizing for splash page header
- New page for coming soon page

Splash page Header

---

Client/src/pages/register/LoginForm.tsx
Client/src/pages/register/SignUpForm.tsx
Client/src/pages/register/VerifyEmail.tsx
Client/src/redux/auth/authSlice.ts
server/src/index.ts

Firebase improvements

---

Client/src/App.tsx
Client/src/components/splashPage/team/PersonCard.tsx
Client/src/components/splashPage/team/Team.tsx
Client/src/helpers/getTeamMembers.ts
Client/src/pages/TeamPage.tsx
server/src/db/models/team/teamCollection.ts
server/src/db/models/team/teamServices.ts
server/src/index.ts
server/src/routes/team.ts
shared/src/types/index.ts
shared/src/types/team/index.ts

- This new feature takes data from MongoDB and displays it on the frontend
- The data is the team members on this project
- I believe this is a good template that shows how to create a new End-To-End feature from MongoDB -> Server -> Frontend

Creating the E2E Team Doc

---

Client/src/components/splashPage/team/JoinTeam.tsx
Client/src/pages/TeamPage.tsx

- New component was added to showcase the google survey @compside created 
- In this google survey we are presenting the opportunity for other engineers to join the team.

Join Team Link Added

---

Client/src/components/register/SignInFlow/index.tsx

- New Users were not allowed to skip the sign in flow

Fixing the signup flow skip

---

Client/src/components/chat/NewChat.tsx
Client/src/components/chatLog/ChatSidebarFooter.tsx
Client/src/components/flowchart/FlowChart.tsx
Client/src/components/flowchart/flowchartFooter/FlowChartFooter.tsx
Client/src/components/flowchart/flowchartHeader/FlowChartHeader.tsx
Client/src/components/flowchart/flowchartSidebar/SidebarFlowchart.tsx
Client/src/components/layout/ChatPage/ChatPageHeader.tsx
Client/src/components/layout/ChatPage/ChatPageSidebar.tsx
Client/src/components/layout/OuterIconSidebar.tsx
Client/src/components/layout/ProfilePage/ProfilePageHeader.tsx
Client/src/components/layout/ProfilePage/ProfilePageLayout.tsx
Client/src/components/layout/SectionPage/SectionPageLayout.tsx
Client/src/components/layout/flowchart/FlowchartLayout.tsx
Client/src/components/ui/sidebar.tsx
Client/src/pages/ChatPage.tsx
Client/src/pages/FlowChatPage.tsx
Client/src/pages/ProfilePage.tsx
Client/src/pages/SectionPage.tsx

New Icon Sidebar that makes it easier to navigate around the app

Double sidebar

---

Client/src/components/section/InstructorRatingFilter.tsx
Client/src/components/section/PaginationFooter.tsx
Client/src/components/section/SectionContainer.tsx
Client/src/components/section/SectionDoc.tsx
Client/src/components/section/SectionFilters.tsx
Client/src/components/userProfile/Interest.tsx
Client/src/redux/section/crudSection.ts
Client/src/redux/section/sectionSlice.ts
server/src/db/models/section/sectionCollection.ts
server/src/db/models/section/sectionServices.ts
server/src/routes/section.ts
server/src/types/express/index.d.ts
shared/src/types/section/index.ts

- Edited the filter section logic and the section result
- New Sections for Spring 2025

Section query logic

---

Client/src/components/chat/ChatInput.tsx

added enter key option

---

Client/src/components/flowchart/helpers/fetchCourses.ts
Client/src/components/layout/SectionPage/SectionPageHeader.tsx
Client/src/components/layout/SectionPage/SectionPageLayout.tsx
Client/src/components/section/SectionDoc.tsx
Client/src/components/section/filterForm/CourseInformation.tsx
Client/src/components/section/filterForm/Instructor.tsx
Client/src/components/section/filterForm/Scheduling.tsx
Client/src/components/section/filterForm/SectionFilters.tsx
Client/src/components/section/filterForm/reusable/CollapsibleContentWrapper.tsx
server/src/db/models/courses/courseServices.ts

Filter courses by their name as well

Course Search Bar Improvement 

---

Client/src/components/section/SectionDoc.tsx
Client/src/pages/SectionPage.tsx

- Section page, where users can search and filter for courses

Releasing Section Page

---

Client/src/components/layout/OuterIconSidebar.tsx

Sign out button located on icon sidebar only when the user is on their profile page

Sign out button

---

Client/src/components/flowchart/EmptyFlowchart.tsx
Client/src/components/flowchart/ProgressBar.tsx
Client/src/components/flowchart/flowchartHeader/FlowChartHeader.tsx
Client/src/components/layout/flowchart/FlowchartLayout.tsx
Client/src/components/register/SignInFlow/FlowChartOptions.tsx
Client/src/components/ui/reusable-dropdown.tsx
Client/src/pages/FlowChatPage.tsx

Empty Flowchart Page:
- added empty page flowchart 
- created progress bar
- fixed flowchart header styling bug

Flowchart Page Styling Improvements

---

Client/src/App.tsx
Client/src/components/flowchart/ProfileEmptyFlowchart.tsx
Client/src/components/flowchart/ProgressBar.tsx
Client/src/components/register/SignInFlow/FlowChartOptions.tsx
Client/src/components/register/SignInFlow/index.tsx
Client/src/pages/ProfilePage.tsx

- Fixed some style issues that occurred from previous commit of Empty Flowchart
- Added Empty Profile Page Flowchart component
- Sign IN flow does not direct student to flowchart page
- Progress bar goes back a step when selects new major

Flowchart bug fixes

---

Client/src/components/layout/OuterIconSidebar.tsx

Sign out option appears when student hovers over the profile icon on the outer icon sidebar

Sign out appears on hover

---

Client/src/components/section/PaginationFooter.tsx
Client/src/components/section/filterForm/QueryAI.tsx
Client/src/components/section/filterForm/SectionFilters.tsx
Client/src/redux/section/crudSection.ts
Client/src/redux/section/sectionSlice.ts
server/src/helpers/assistants/queryAgent.ts
server/src/routes/llm.ts
server/src/routes/section.ts
shared/src/types/section/index.ts

- Redefined system instructions & function tooling on the openAI assistant playground 
- Zod Flexible Schema Validator
- Pagination Separation between manual filtering and AI filtering
- Combining AI filters with manual filters

Query ai improvements

---

Client/src/components/flowchart/EmptyFlowchart.tsx
Client/src/components/flowchart/FlowChart.tsx
Client/src/components/flowchart/flowchartFooter/FlowChartFooter.tsx
Client/src/components/flowchart/flowchartHeader/FlowChartHeader.tsx
Client/src/components/flowchart/flowchartSidebar/SidebarFlowchart.tsx
Client/src/components/register/SignInFlow/index.tsx
Client/src/components/section/filterForm/QueryAI.tsx
Client/src/pages/FlowChatPage.tsx
Client/src/pages/ProfilePage.tsx
Client/src/redux/flowchart/api-flowchart.ts
Client/src/redux/flowchart/flowchartSlice.ts
server/src/helpers/assistants/prereqValidator.ts

- Auto select courses based on student's year
- Auto update flowchart

Flowchart auto

---

Client/package.json
Client/src/components/calendar/CalendarContainer.tsx
Client/src/components/calendar/CalendarSideOptions.tsx
Client/src/components/calendar/SectionsChosen.tsx
Client/src/components/calendar/SelectedSectionContainer.tsx
Client/src/components/calendar/WeeklyCalendar.tsx
Client/src/components/section/CalendarTimeSlots.tsx
Client/src/components/section/SectionDoc.tsx
Client/src/helpers/transformSection.ts
Client/src/index.css
Client/src/pages/CalendarPage.tsx
Client/src/redux/sectionSelection/crudSelectionSection.ts
Client/src/redux/sectionSelection/sectionSelectionSlice.ts
package-lock.json
server/src/db/models/selectedSection/sectionServices.ts
server/src/db/models/selectedSection/selectedSectionCollection.ts
server/src/routes/selectedSection.ts
shared/src/types/section/index.ts
shared/src/types/selectedSection/index.ts

Weekly Calendar 

---

Client/src/components/chatLog/ChatLog.tsx
Client/src/components/chatLog/ChatLogOptions.tsx

previously, if we tried to rename a chat log and pressed save, the popover wouldn't actually disappear. Now, if we click save, the popover disappears

added state to handle renaming

---

Client/src/components/layout/ProfilePage/ProfilePageLayout.tsx
Client/src/components/splashPage/MatchingFeatures.tsx
Client/src/components/ui/sticky-scroll-reveal.tsx
Client/src/pages/ProfilePage.tsx
Client/src/redux/section/crudSection.ts

Splash page improvements

---

Client/src/components/calendar/helpers/buildSchedule.ts

- Improved Schedule Builder Algo to handle conflicted time and courses

Build Schedule Algorithm

---

Client/src/components/ui/sidebar.tsx

when the user refreshes the page or navigates to flowchart, the sidebar will remain consistent with what they previously had

sidebar open and close

---

Client/src/components/calendar/BuildScheduleContainer.tsx
Client/src/components/calendar/CalendarAIChatContainer.tsx
Client/src/components/calendar/CalendarContainer.tsx
Client/src/components/calendar/PaginationFooter.tsx
Client/src/components/flowchart/flowchartSidebar/SidebarFlowchart.tsx
Client/src/components/layout/CalendarPage/CalendarPageLayout.tsx
Client/src/components/layout/ChatPage/ChatPageSidebar.tsx
Client/src/components/layout/MobileHeader.tsx
Client/src/components/layout/ProfilePage/ProfilePageLayout.tsx
Client/src/components/layout/SectionPage/SectionPageLayout.tsx
Client/src/components/layout/flowchart/FlowchartLayout.tsx
Client/src/components/section/PaginationFooter.tsx
Client/src/components/section/SectionContainer.tsx
Client/src/components/section/filterForm/SectionFilters.tsx
Client/src/pages/CalendarPage.tsx
Client/src/pages/ChatPage.tsx
Client/src/pages/FlowChatPage.tsx
Client/src/pages/SectionPage.tsx

Using a header to replace the outer icon sidebar when the screen width is small

Small Width devices layouts

---

Client/src/pages/ChatPage.tsx

Shoutout @jhueyy for finding this bug
- New chats would not work because the assistant list would not update it in the use effect

Bug fix: Chat Page Bug Fix 

---

server/src/helpers/assistants/multiAgent.ts
server/src/helpers/assistants/multiAgentHelpers/professorRatings.ts

Fixed bug for professor rarings

New changes

---

server/src/db/models/section/sectionCollection.ts
server/src/helpers/assistants/multiAgent.ts
server/src/helpers/assistants/multiAgentHelpers/ScheduleBuilderFunctions/fetchHandlers.ts
server/src/helpers/assistants/multiAgentHelpers/ScheduleBuilderFunctions/queryType.ts
server/src/helpers/assistants/multiAgentHelpers/scheduleBuilder.ts
server/src/index.ts
shared/src/types/llm/index.ts

Multi agent assistants improved

Schedule builder assistant enhanced

---

Client/src/helpers/transformSection.ts

When there are multiple instructors teaching a section, we should display the section n amount of times where n = number of teachers in that single section

Fix multiple instructors bug

---

README.md
documentation/full-stack-tutorial.md

- Added some docs to implement a full stack feature 
None

Full stack tutorial docs

---

Client/src/components/layout/ChatPage/ChatPageSidebar.tsx
Client/src/components/section/layout/SectionContainer.tsx
Client/src/components/ui/sidebar.tsx

From previous commit, a bug was introduced for tablet devices. This is now fixed
- This does not fix the pagination footer bug 
Fixing bug introduced from the previous pr #221 
Closes #
-
-
-

Fixed chat page sidebar ui bug

---

server/src/helpers/assistants/mongoSectionQuery/sectionQuerySchema.ts
server/src/helpers/assistants/mongoSectionQuery/sectionQuerySyststemInstructions.ts
server/src/helpers/assistants/queryAgent.ts
server/src/routes/section.ts

- Improved the response time for the MongoDB Query 
- Students can now search for classes using the AI with improved response times
Closes #223 
- Shifted away from the usage of openAI Assistants and transitioned to chat completions 
- Created a define schema for the returned json schema 
- Moved the system instructions into a file on the backend

AI Migrating for MongoDB Query Assistant

---

Client/src/components/calendar/weeklyCalendar/emptyState/EmptyCalendar.tsx
Client/src/components/chat/chatFooter/ChatInput.tsx
Client/src/components/layout/OuterIconSidebar.tsx
Client/src/components/splashPage/MatchingFeatures.tsx
Client/src/components/splashPage/about/aboutText.ts
Client/src/pages/CalendarPage.tsx
Client/src/redux/message/crudMessage.ts
README.md

On client side and in docs, we need to rename schedule builder to schedule analysis
On previous PR #227 I forgot to rename on client folder and in docs
Closes #
-
-
-

Renaming Schedule Builder to Schedule Analysis

---

server/src/helpers/assistants/SectionQuery/sectionQuerySyststemInstructions.ts

For section query asst, we are adding into the query asst to pattern match based on regex exp

Allow regex pattern matching

---

Client/src/components/section/currentSectionList/SectionDoc.tsx

This PR improves the layout of the section list on the course catalog page for better responsiveness on smaller screens. It dynamically adjusts fonts, spacing, and layout to enhance readability and usability on mobile devices.
Closes #230 
- Adjusted header section to stack elements vertically on mobile and resized fonts.
- Optimized course section layout to ensure proper spacing and legibility on smaller screens.
- Modified lecture/lab section pairing to stack vertically on screens <768px and display side-by-side on larger screens.
- Improved general layout by adjusting padding, preventing horizontal scrolling, and maintaining content hierarchy.

Improved Dynamic Layout for Section List

---

Client/src/components/chat/chatFooter/ChatInput.tsx
Client/src/components/flowchart/currentFlowchart/FlowChart.tsx
Client/src/components/flowchart/currentFlowchart/TermContainer.tsx
Client/src/components/flowchart/layout/FlowchartUnitCounts.tsx
Client/src/components/layout/FlowchartPage/FlowchartHeader.tsx
Client/src/components/layout/FlowchartPage/FlowchartLayout.tsx
Client/src/pages/register/SignUpForm.tsx

- Added disclaimers to improve transparency to students 
- Modified some of the layout styles for the flowchart page
Closes #239 
- Modified the sticky footer for the chat page and flowchart page
- Added a small disclaimer
-

[Feature-Add-Disclaimers] Adding Disclaimers to Chat Page and Flowchart Page 

---

Client/src/components/chat/chatFooter/ChatInput.tsx
server/src/helpers/assistants/multiAgent.ts
server/src/helpers/assistants/singleAgent.ts
server/src/routes/llm.ts

- For lengthy conversations, we are locking the chat log so no more messages can be sent 
- Client & Server protection with error handling on both ends 
Closes #241 
- **Client**: Added a state var that updates when the chat log reaches a certain length. Removes ability to type 
- **Server**: Added check to verify chat log length is under a specific amount in the llm respond route
- **Error Handling**: Return status 429 from server if chat log is over. This call shouldn't be passed from client but is added as a safe guard 
- Renamed chatId to `logId` to match naming conventions from the mongoDB collection

Feature lock chat conversations

---

server/src/routes/llm.ts

- Fixed bug for new chat logs introduced in previous PR.

Bug Fix New Chat Logs

---

Client/src/components/chat/chatFooter/ChatInput.tsx
Client/src/redux/log/crudLog.ts
Client/src/redux/log/logSlice.ts
Client/src/redux/message/crudMessage.ts
Client/src/redux/message/messageSlice.ts
server/src/helpers/assistants/createTitle/createTitle.ts
server/src/helpers/assistants/helpAssistant/helpAssistant.ts
server/src/helpers/assistants/multiAgent.ts
server/src/helpers/assistants/multiAgentHelpers/streamResponse.ts
server/src/helpers/assistants/singleAgent.ts
server/src/helpers/auth/verifyAuth.ts
server/src/routes/chatLog.ts
server/src/routes/llm.ts
server/tsconfig.json
shared/src/types/log/index.ts
shared/src/types/message/index.ts

- Refactoring the code for llm respond so that we have a better unified backend
- Combined Create and Update for Upsert 
Closes #
-
-
-

Refactor llm respond

---

Client/tsconfig.json
package-lock.json
package.json

client ts config

---

Client/src/components/flowchart/currentFlowchart/FlowChart.tsx
Client/src/components/flowchart/currentFlowchart/TermContainer.tsx
Client/src/components/layout/dnd/DragDropContextWrapper.tsx

- Fixed two bugs for the flowchart
1. Term Year offset updated correctly
2. Drag and drop from sidebar fixed 
Closes #
-
-
-

Bug term year offset

---

Client/src/components/chat/chatSideBar/AssistantItem.tsx
Client/src/components/chat/chatSideBar/AssistantSelector.tsx
Client/src/components/chat/chatSideBar/SideBarDropDown.tsx
Client/src/components/chat/helpers/handleModeSelection.ts
Client/src/components/layout/ChatPage/ChatPageHeader.tsx
Client/src/components/layout/ChatPage/ChatPageSidebar.tsx

Created an assistant selector on the sidebar
Closes #205 
- I created a new component in src/components/chat/chatSidebar/AssistantSelector.tsx which makes use of another new component AssistantItem from AssistantItem.tsx
- I also extracted and exported the handleModeSelection function to reduce duplicate code, and used it in the chatPageSidebar
- AssistantItem should be reusable if needed elsewhere, it is just one assistant
- I also made the sidebar drop down go into a new group and menu 
https://github.com/user-attachments/assets/e4a094e5-c892-43fa-a5af-76bdd2257fa7
- There is a somewhat hard to reproduce bug when reducing window size while sidebar is open. If you close it real slow ir gets stuck on the side. It doesn't happen in regular use case and is not a noticeable issue, but is …

Issue 205 sidebar ai selection

---

Client/src/components/chatLog/ChatLogList.tsx
Client/src/components/layout/ChatPage/ChatPageSidebar.tsx
Client/src/components/section/courseFilters/SectionForm.tsx
Client/src/components/section/layout/PaginationFooter.tsx
Client/src/pages/CalendarPage.tsx
Client/src/pages/ChatPage.tsx
Client/src/pages/FlowchartPage.tsx
Client/src/pages/ProfilePage.tsx
Client/src/pages/SectionPage.tsx

- For multiple components, we have duplicate data fetching when the page reloads for the first time.
- This can cause some performance issues. 
- This was fixed for each page in this PR. 
Closes #
- Added refs that allow us to check if the data has already been fetched before we dispatch the action that will fetch this data.
-
-

Performance improvement data fetching

---

Client/src/components/flowchart/flowchartSidebar/SidebarFlowchart.tsx
Client/src/components/flowchart/index.ts
Client/src/components/flowchart/layout/CreateFlowchart.tsx
Client/src/components/layout/FlowchartPage/FlowchartLayout.tsx
Client/src/pages/FlowchartPage.tsx
Client/src/redux/flowchart/flowchartSlice.ts

- Create  Menu implemented from the previous Empty Flowchart state 
Closes #
- Renamed Empty Flowchart component to `CreateFlowchart`
- Added a state variable that is dispatched to `true` when the user wants to create a new flowchart
- Dispatch to `false` when there is a flowchart the user would like to view (existing or new)
-

Create Menu Simplified

---

Client/src/components/flowchart/createFlowchart/FlowChartOptions.tsx
Client/src/components/flowchart/createFlowchart/ProgressBar.tsx
Client/src/components/flowchart/currentFlowchart/FlowChart.tsx
Client/src/components/flowchart/layout/CreateFlowchart.tsx
Client/src/redux/flowchart/api-flowchart.ts

- Added an option to allow a flowchart to be created with a starting year
Closes #
- Added the dropdown to select a starting year when creating a flowchart
- Modified the progress bar to have a starting year (4 steps now instead of 3)
- Updated flowchart reflects the selected flowchart before we save to database and write into state

[Feature-Flowchart-Starting-Year] Added Option for Starting Year to create a flowchart

---

Client/package.json
Client/src/components/flowchart/flowchartSidebar/SidebarFlowchart.tsx
Client/src/redux/flowchart/flowchartSlice.ts
package-lock.json
shared/package.json

- Hide flowchart unit count footer if there is no flowchart data being displayed 
- Also used this pr to make adjustments to the typescript version we are using and made it the same for each workspace 
Closes #
-
-
-

Flowchart footer hidden

---

Client/src/components/flowchart/currentFlowchart/CourseTooltipContent.tsx
Client/src/components/flowchart/currentFlowchart/TermContainer.tsx
Client/src/redux/flowchart/api-flowchart.ts
shared/src/types/flowChart/index.ts

- Display flowchart notes from `addl`
Closes #
- For new flowcharts being created, we set each course to add notes 
-
-

Display notes from flowchart

---

Client/src/components/register/SignInFlow/BasicInformation.tsx
Client/src/components/register/SignInFlow/Demographics.tsx
Client/src/components/register/SignInFlow/DesktopSignInFlow.tsx
Client/src/components/register/SignInFlow/InputInformation.tsx
Client/src/components/register/SignInFlow/Interests.tsx
Client/src/components/register/SignInFlow/MobileSignInFlow.tsx
Client/src/components/register/SignInFlow/Terms.tsx
Client/src/components/register/SignInFlow/index.tsx
Client/src/components/register/TitleCard.tsx

- Improved the layout structure for the sign in flow for mobile device 
- 
Closes #
- Created a new layout component for sign in flow for mobile devices
- Modified the sign in flow components to be more responsive to mobile devices and smaller devices 
-

Enhancement mobile sign in flow

---

Client/src/components/register/SignInFlow/BasicInformation.tsx
Client/src/pages/ProfilePage.tsx
Client/src/pages/register/SignUpForm.tsx
Client/src/redux/auth/authSlice.ts
Client/src/redux/auth/crudAuth.ts
Client/src/redux/flowchart/api-flowchart.ts
server/src/db/models/signupAccess/signupAccessServices.ts
server/src/routes/auth.ts
shared/src/types/user/index.ts

- To prepare for Open House, I am pushing a change that will only be open for a week to allow non cal poly users to sign up with a passphrase if they do not have access to a student email yet.
Closes #
-
-
-

Non calpoly users signup

---

Client/src/components/flowchart/createFlowchart/CreateFlowchart.tsx
Client/src/components/flowchart/currentFlowchart/FlowChart.tsx
Client/src/components/layout/FlowchartPage/MobileFlowchartLayout.tsx
Client/src/pages/FlowchartPage.tsx

Flowchart mobile bugs

---

Client/src/components/classSearch/courseFilters/courseInformation/CourseInformation.tsx
Client/src/components/classSearch/currentSectionList/SectionCourseDropdown.tsx
Client/src/components/flowchart/flowchartSidePanel/courses/CourseDropdown.tsx
Client/src/components/flowchart/flowchartSidePanel/courses/CourseSearchbar.tsx
Client/src/components/flowchart/flowchartSidePanel/courses/SidebarCourse.tsx
Client/src/components/flowchart/helpers/fetchCourses.ts
Client/src/components/flowchart/helpers/findCatalogYear.ts
Client/src/components/flowchart/index.ts
server/src/db/models/courses/courseServices.ts

- Course search bar display is improved
- Have the courseId and display name
- Also implemented a function to find the catalog for each flowchart 
Closes #
-
-
-

Course Search Bar Display Courses

---

Client/src/components/flowchart/flowchartSidePanel/courses/CourseDropdown.tsx
Client/src/components/flowchart/flowchartSidePanel/courses/GeDropdown.tsx
Client/src/components/flowchart/helpers/fetchCourses.ts
Client/src/components/layout/dnd/DragDropContextWrapper.tsx
server/src/db/models/courses/courseCollection.ts
server/src/db/models/courses/courseFormatter.ts
server/src/db/models/courses/courseServices.ts
server/src/db/models/courses/geCollection.ts
server/src/routes/courses.ts
shared/src/types/courses/index.ts

- In the Flowchart page, we are now listing the GE areas in a hierarchical dropdown structure
- Users can browse GE courses by area and subject, with data loaded progressively as needed
- The component implements a three-stage data fetching approach to optimize performance
Closes #
- 3 new API endpoints were made (fetch GE Area names, fetch GE subject names by GE Area, fetch GE Course Objects by GE Area and GE subject)
- We should avoid fetching all GE Courses because this could slow down the website and be problematic, so we only fetch the minimum amount of data necessary 
- Implemented a hierarchical dropdown component for GE courses with three levels:
- GE Areas (e.g., A1, A2, etc.)
- Subjects within each area (e.g., COMS, ENGL, etc.)
- Courses within each subject
- Added loading …

[Flowchart-GE-Dropdown]: Flowchart List GE Dropdowns 

---

Client/src/components/flowchart/currentFlowchart/FlowChart.tsx
Client/src/components/flowchart/currentFlowchart/TermContainer.tsx
Client/src/components/flowchart/currentFlowchart/YearSelector.tsx
Client/src/components/layout/FlowchartPage/MobileFlowchartLayout.tsx
Client/src/pages/FlowchartPage.tsx
server/src/db/models/courses/courseServices.ts

This PR improves the visual design of the YearSelector component by making it more modern and cleaner looking. The changes focus on reducing visual weight while maintaining good usability.
Closes #N/A
- Reduced the height of the year selector tabs by adjusting vertical padding
- Made borders more subtle by:
- Using opacity modifiers for border colors
- Lightening the border color from slate-800 to slate-700
- Improved text styling:
- Reduced text size from base to sm for better proportions
- Added subtle opacity to inactive tab text
- Enhanced visual feedback:
- Added hover effect with smooth transition
- Made background colors semi-transparent
- Improved active state visibility while maintaining subtlety
Before:
- Taller tabs with solid borders
- Larger text size
- More prominent visual …

Flowchart year selector tabs

---

Client/src/components/flowchart/flowchartSidePanel/courses/CourseDropdown.tsx
Client/src/components/flowchart/flowchartSidePanel/courses/GeDropdown.tsx
Client/src/components/flowchart/flowchartSidePanel/courses/TechElectiveDropdown.tsx
Client/src/components/flowchart/helpers/fetchCourses.ts
server/src/db/models/courses/courseCollection.ts
server/src/db/models/courses/courseFormatter.ts
server/src/db/models/courses/courseServices.ts
server/src/db/models/courses/techElectiveCollection.ts
server/src/db/models/flowInfo/flowInfoServices.ts
server/src/routes/courses.ts
shared/src/types/courses/index.ts

Implemented a comprehensive tech elective course selection system that allows users to browse and select tech elective courses based on their major, concentration, and catalog year. The system includes both backend services to fetch course data and a frontend dropdown component for user interaction.
Closes #N/A
- Created new API endpoints in `server/src/routes/courses.ts`:
- `GET /techElective/info/:code` - Returns basic information about tech electives for a major
- `GET /techElective/subjects/:category/:code` - Returns subject codes for a tech elective category
- `GET /techElective/:subject/:category/:code` - Returns courses for a specific subject and category
- `GET /techElective/details/:subject/:category/:code` - Returns detailed course information
- Implemented service functions in …

Flowchart tech electives

---

Client/src/components/flowchart/flowchartSidePanel/courses/SidebarCourse.tsx
Client/src/components/flowchart/flowchartSidePanel/courses/TechElectiveDropdown.tsx
Client/src/components/layout/dnd/DragDropContextWrapper.tsx
Client/src/pages/FlowchartPage.tsx
Client/src/redux/flowchart/flowchartSlice.ts

[Flowchart class colors]: Adding Completed Styles to Side Panel Courses

---

Client/src/components/calendar/buildSchedule/layout/LeftScheduleFooter.tsx
Client/src/components/classSearch/courseFilters/SectionForm.tsx
Client/src/components/classSearch/courseFilters/courseInformation/CourseInformation.tsx
Client/src/components/classSearch/reusable/filter/SearchBar.tsx
Client/src/components/flowchart/flowchartSidePanel/courses/CourseSearchbar.tsx
Client/src/components/flowchart/flowchartSidePanel/courses/SidebarCourse.tsx
Client/src/components/flowchart/helpers/fetchCourses.ts
Client/src/redux/classSearch/classSearchSlice.ts

Fixed two issues in the codebase: a React rendering error in the SearchBar component and display error with the `CommandInput` for the `CourseSearchbar` component 
Closes #N/A
- Fixed a React rendering error in the SearchBar component where objects were being rendered directly as React children
- Modified the CommandItem to properly display course information using template literals
- Changed the value and display format to use `${item.courseId} - ${item.displayName}`
- Similar change for `CourseSearchbar.tsx`
- Fixed the fetchData prop in the CourseInformation component
- Changed from passing the result of `fetchCoursesAPI("2022-2026", "")` to passing a function that calls `fetchCoursesAPI` with the input value
- This ensures the search input value is properly passed to the API
N/A
These …

Class search bugs

---

Client/src/components/scheduleBuilder/buildSchedule/layout/LeftScheduleFooter.tsx
Client/src/components/scheduleBuilder/weeklySchedule/WeeklySchedule.tsx

Schedule builder layout

---

Client/src/components/classSearch/currentSectionList/SectionInfo.tsx
Client/src/components/scheduleBuilder/buildSchedule/selectedSections/SectionsChosen.tsx
Client/src/components/scheduleBuilder/helpers/groupingSections.ts
Client/src/pages/ScheduleBuilder.tsx
Client/src/redux/sectionSelection/crudSelectionSection.ts
Client/src/redux/sectionSelection/sectionSelectionSlice.ts
server/src/db/models/section/sectionServices.ts
server/src/db/models/selectedSection/sectionServices.ts
server/src/db/models/selectedSection/selectedSectionCollection.ts
server/src/db/models/selectedSection/selectedSectionServices.ts
server/src/routes/selectedSection.ts
shared/src/types/selectedSection/index.ts

Save Selected Sections Improvement

---

Client/src/components/flowchart/flowchartSidePanel/FlowchartBuilderForm.tsx
Client/src/components/flowchart/flowchartSidePanel/flowchartInfo/FlowchartInfo.tsx
Client/src/redux/flowSelection/flowSelectionSlice.ts
Client/src/redux/flowchart/flowchartSlice.ts
server/src/db/models/flowInfo/flowInfoServices.ts
server/src/db/models/flowchart/flowchartCollection.ts
server/src/db/models/flowchart/flowchartServices.ts
server/src/routes/flowInfo.ts
shared/src/types/flowChart/index.ts

This PR enhances the FlowchartInfo component in the side panel to display flowchart information in a more compact, visually appealing way. The component now shows key flowchart details with improved layout and styling.
Closes #N/A
- Redesigned the FlowchartInfo component with a more compact layout
- Implemented vertical stacking for labels and values to improve readability
- Added Framer Motion animations for a smoother user experience
- Improved responsive design for both wide and narrow screens
- Enhanced visual styling with better spacing, typography, and color contrast
- Added a "View Official Flowchart" button that opens the flowchart PDF in a new tab
- Displayed key flowchart information including Major, Concentration, and Catalog
- Optimized the component to take up minimal space …

Flowchart Info added

---

Client/src/components/scheduleBuilder/buildSchedule/selectedSections/SectionsChosen.tsx
server/src/routes/flowInfo.ts

This PR improves the responsive layout of the SectionsChosen component, particularly focusing on the time and remove button section to ensure better usability on narrow screens within a side panel.
Closes #N/A
- Improved the styling of the course header section by removing the dark background and adding a subtle bottom border
- Enhanced the sections count badge with a cleaner, more subtle design
- Made the component fully responsive within its parent container by adding proper width constraints
- Implemented a flexible layout for the time and remove button section using `flex-wrap`
- Ensured the remove button remains accessible even on narrow screens by allowing it to wrap to a new line when needed
- Added proper truncation for course IDs to prevent overflow on narrow screens
- Optimized …

Sections Chosen Updated Styles

---

Client/src/components/scheduleBuilder/helpers/formatting.ts
Client/src/components/scheduleBuilder/helpers/index.ts
Client/src/components/scheduleBuilder/helpers/scheduleTransformers.ts
Client/src/components/scheduleBuilder/helpers/weeklyCalendarConflicts.ts
Client/src/components/scheduleBuilder/layout/ScheduleContainer.tsx
Client/src/components/scheduleBuilder/weeklySchedule/ScheduleTimeSlots.tsx
Client/src/components/scheduleBuilder/weeklySchedule/WeeklySchedule.tsx

This PR improves the weekly schedule display by reducing the height of time slots and enhancing the time and professor name formatting. These changes make the schedule more compact and readable, with proper 12-hour time format and professor name display.
Closes #N/A
- **Time Slot Height Reduction**:
- Modified the FullCalendar component in `WeeklySchedule.tsx` to use 1-hour time slots instead of 30-minute slots
- Adjusted CSS properties to reduce the overall height of the calendar
- Implemented responsive height calculations based on window size and container dimensions
- Added CSS custom properties for consistent spacing and padding
- **Time and Professor Name Formatting**:
- Created a new utility file `timeFormatting.ts` with functions for time format conversion
- Implemented …

Weekly schedule layout

---

Client/src/components/scheduleBuilder/buildSchedule/ScheduleBuilderForm.tsx
Client/src/components/scheduleBuilder/buildSchedule/savedSchedules/ScheduleOptions.tsx
Client/src/components/scheduleBuilder/buildSchedule/selectedSections/SectionsChosen.tsx
Client/src/pages/ScheduleBuilder.tsx
Client/src/redux/sectionSelection/sectionSelectionSlice.ts
server/src/db/models/selectedSection/selectedSectionCollection.ts
server/src/routes/selectedSection.ts

This PR adds functionality to select and deselect sections for schedule building, with improvements to the user experience when adding and removing sections.
Closes # (Section Selection for Schedule Building)
- Added the `term` property to the `SelectedSection` type to properly track which term a section belongs to
- Implemented `selectAllSectionsForSchedule` and `deselectAllSectionsForSchedule` actions in the section selection slice
- Added UI controls to select/deselect all sections for a specific term
- Fixed an infinite loop in the `ScheduleBuilderForm` component when updating preferences
- Implemented optimistic UI updates when removing sections to provide immediate feedback
- Added defensive programming to handle edge cases when `sectionsForSchedule` is not an array
- Ensured that …

Deselect Selected Sections Added

---

Client/src/components/scheduleBuilder/buildSchedule/ScheduleBuilderForm.tsx
Client/src/components/scheduleBuilder/buildSchedule/savedSchedules/SavedSchedules.tsx
Client/src/components/scheduleBuilder/buildSchedule/selectedSections/SelectedSectionContainer.tsx
Client/src/components/scheduleBuilder/weeklySchedule/NarrowScreenScheduleSectionInfo.tsx
Client/src/components/scheduleBuilder/weeklySchedule/ScheduleTimeSlots.tsx
Client/src/components/scheduleBuilder/weeklySchedule/WeeklySchedule.tsx
Client/src/components/ui/animated-modal.tsx
Client/src/index.css

Weekly schedule responsive layout

---

Client/src/components/scheduleBuilder/index.ts
Client/src/components/scheduleBuilder/layout/ScheduleContainer.tsx
Client/src/components/scheduleBuilder/weeklySchedule/AsyncCourses.tsx
Client/src/components/scheduleBuilder/weeklySchedule/NarrowScreenScheduleSectionInfo.tsx
Client/src/components/scheduleBuilder/weeklySchedule/ScheduleSectionInfo.tsx
Client/src/components/scheduleBuilder/weeklySchedule/ScheduleTimeSlots.tsx
Client/src/components/scheduleBuilder/weeklySchedule/WeeklySchedule.tsx
Client/src/components/ui/animated-modal.tsx

This PR implements a dynamic AsyncCourses component that displays asynchronous courses in a compact, responsive grid layout. It also ensures the WeeklySchedule calendar height adjusts dynamically based on the AsyncCourses component's expanded/collapsed state, preventing layout issues when toggling the async courses section.
- Created a new AsyncCourses component that displays asynchronous courses in a compact grid layout
- Implemented responsive grid columns that adjust based on the number of async courses (1-6 columns)
- Added a collapsible interface with smooth animations using Framer Motion
- Positioned professor names at the bottom left of each course card
- Optimized text sizes for different screen sizes (smaller on mobile, larger on desktop)
- Added hover and click interactions for …

Weekly calendar async courses

---

Client/src/components/scheduleBuilder/layout/ScheduleContainer.tsx
Client/src/components/scheduleBuilder/weeklySchedule/ScheduleTimeSlots.tsx
Client/src/components/scheduleBuilder/weeklySchedule/WeeklySchedule.tsx
Client/src/components/ui/animated-modal.tsx
Client/src/pages/ProfilePage.tsx

Profile page weekly calendar

---

Client/src/components/flowchart/currentFlowchart/FlowChart.tsx
Client/src/components/flowchart/currentFlowchart/FullScreenCourseItem.tsx
Client/src/components/flowchart/currentFlowchart/FullScreenFlowchart.tsx
Client/src/components/flowchart/currentFlowchart/FullScreenTermContainer.tsx
Client/src/components/flowchart/currentFlowchart/YearSelector.tsx
Client/src/redux/flowchart/flowchartSlice.ts

This PR implements a full timeline view for the flowchart, allowing users to see all terms at once in a horizontal layout. The implementation includes responsive design for different screen sizes and maintains visual consistency with the existing flowchart components.
Closes #N/A
- Created a new `FullScreenFlowchart` component that displays all terms in a horizontal layout
- Implemented `FullScreenTermContainer` component with consistent styling to match the regular `TermContainer`
- Developed `FullScreenCourseItem` component with improved visual design and layout
- Added responsive design for mobile devices with horizontal scrolling
- Implemented a toggle mechanism in the `Flowchart` component to switch between regular and full-screen views
- Added a "Full Timeline" button in the …

flowchart full timeline display

---

Client/src/redux/classSearch/classSearchSlice.ts
Client/src/redux/classSearch/crudClassSearch.ts
server/src/routes/llm.ts

- There was a bug in the AI class search when searching for summer sections
- This bug would make it only search for spring2025 sections even if we were on the summer 2025 section
Closes #
- Added a url endpoint parameter for the term
- The term tells us what collection we should be looking into
-

BUG FIX: AI Class search Term Filtering

---

Client/src/components/classSearch/courseFilters/scheduling/Scheduling.tsx
Client/src/components/scheduleBuilder/buildSchedule/ScheduleBuilderForm.tsx
Client/src/components/scheduleBuilder/buildSchedule/layout/BuildScheduleContainer.tsx
Client/src/components/scheduleBuilder/buildSchedule/savedSchedules/SavedSchedules.tsx
Client/src/components/scheduleBuilder/buildSchedule/savedSchedules/ScheduleOptions.tsx
Client/src/components/userProfile/ProfileEmptyState.tsx
Client/src/pages/ScheduleBuilder.tsx
Client/src/redux/schedule/crudSchedule.ts
Client/src/redux/schedule/scheduleSlice.ts
server/src/db/models/schedule/scheduleCollection.ts
server/src/db/models/schedule/scheduleListCollection.ts
server/src/db/models/schedule/scheduleServices.ts
server/src/routes/schedule.ts

This PR implements a series of improvements to the schedule management system, focusing on proper state management, navigation, and user feedback. The changes ensure consistent behavior when creating, updating, and viewing schedules.
Closes #
- Added `updateScheduleName` service function to handle both Schedule and Schedule List collection updates
- Implemented proper error handling and status codes for schedule updates
- Preserved original `createdAt` and `name` during schedule updates
- Added `currentScheduleId` to Redux state for tracking active schedule
- Implemented proper ID management in create/update operations
- Added server-side sorting of schedules (primary schedule first, then by most recent updates)
- Moved navigation logic from `ScheduleBuilderForm` to `ScheduleBuilder` page …

Updating schedule

---

Client/src/components/scheduleBuilder/layout/ScheduleContainer.tsx
Client/src/components/scheduleBuilder/weeklySchedule/AsyncCourses.tsx
Client/src/components/scheduleBuilder/weeklySchedule/WeeklySchedule.tsx
Client/src/index.css
Client/src/pages/ProfilePage.tsx

This PR improves the layout and responsiveness of the WeeklySchedule component, fixing issues with component overlap and scroll behavior. The changes ensure proper spacing between components and prevent the calendar from covering the pagination footer.
Closes # [Add issue number]
- Fixed calendar overflow into pagination footer by:
- Increasing footer space calculation from 3.5rem to 5rem
- Adjusting container max height from `calc(100vh-16rem)` to `calc(100vh-18rem)`
- Setting FullCalendar height to "auto" for better container control
- Improved component layout structure:
- Added `flex-none` to AsyncCourses container to prevent it from growing
- Restructured ScheduleContainer to use proper flex layout
- Removed absolute positioning in favor of flex-based layout
- Added proper spacing …

Weekly schedule simplify layout

---

Client/src/components/scheduleBuilder/buildSchedule/selectedSections/SectionsChosen.tsx
Client/src/components/scheduleBuilder/weeklySchedule/AsyncCourses.tsx
Client/src/components/scheduleBuilder/weeklySchedule/WeeklySchedule.tsx
Client/src/pages/ProfilePage.tsx

Added visibility toggle functionality to both the main course sections and asynchronous courses, allowing users to hide/show sections from their schedule view. Implemented a two-level visibility control system with both course-level and individual section-level toggles.
Closes #
- Added eye icon and visibility toggle functionality to `SectionsChosen.tsx`:
- Added course-level eye icon that controls visibility for all sections of a course
- Added individual section-level eye icons for fine-grained control
- Implemented logic to ensure both levels of control work together
- Added proper state management for hidden sections
- Added eye icon and visibility toggle functionality to `AsyncCourses.tsx`:
- Added eye icon to each async course card
- Implemented the same visibility toggle behavior …

Build schedule nits

---

.deployment
.github/workflows/main_polylink.yml
server/package.json
server/src/helpers/assistants/scheduleBuilder/scheduleBuilderAgent.ts
server/src/routes/test.ts

new approach for deployingf server

---

Client/src/components/scheduleBuilder/aiChat/ScheduleBuilderLogs.tsx
Client/src/components/scheduleBuilder/aiChat/ScheduleLogsOptions.tsx
Client/src/redux/scheduleBuilderLog/crudScheduleBuilderLog.ts
Client/src/redux/scheduleBuilderLog/scheduleBuilderLogSlice.ts
server/src/db/models/scheduleBuilderLog/scheduleBuilderLogCollection.ts
server/src/db/models/scheduleBuilderLog/scheduleBuilderLogServices.ts
server/src/routes/scheduleBuilder.ts

Added functionality to update and delete schedule builder logs, including backend endpoints, services, and frontend integration.
- Added PATCH endpoint `/schedule-builder/logs/:threadId/title` for updating log titles
- Added DELETE endpoint `/schedule-builder/logs/:threadId` for deleting logs
- Added `updateLogTitle` service function in `scheduleBuilderLogServices.ts`
- Added `updateLogTitle` collection function in `scheduleBuilderLogCollection.ts`
- Added `updateLogTitleFromDB` CRUD function in `crudScheduleBuilderLog.ts`
- Added `updateLogTitle` Redux thunk in `scheduleBuilderLogSlice.ts`
- Added loading and error state handling for title updates
- Updated `ScheduleLogsOptions` component to use the new update and delete functionality
N/A
The changes maintain consistency with existing …

Schedule builder logs

---

Client/src/components/classSearch/reusable/filter/UnitSlider.tsx
Client/src/components/scheduleBuilder/buildSchedule/preferences/Preferences.tsx
Client/src/components/scheduleBuilder/helpers/generateAllScheduleCombinations.ts
Client/src/components/scheduleBuilder/helpers/groupingSections.ts
Client/src/components/scheduleBuilder/helpers/scheduleWithConflicts.ts

Improved schedule generation and sorting logic to better handle course combinations and prioritize higher unit schedules.
Closes #XXX 
- **Improved Schedule Generation Logic**:
- Added ability to skip courses at any level in the recursion
- Implemented better conflict handling by checking before recursing
- Simplified the recursion pattern to a single entry point
- Added early pruning for unit limits
- **Enhanced Unit Handling**:
- Added `getSectionUnits` helper function to parse unit strings
- Implemented unit-based pruning during schedule generation
- Added support for both single values and ranges in unit strings
- **Improved Sorting Logic**:
- Changed sorting to prioritize total units first
- Added average rating as a tiebreaker for schedules with equal units
- Applied consistent …

Generate schedule bugs

---

Client/package.json
Client/src/App.tsx
Client/src/components/classSearch/currentSectionList/SectionDoc.tsx
Client/src/components/classSearch/reusable/filter/DoubleSliderFilter.tsx
Client/src/components/classSearch/reusable/filter/FormSwitch.tsx
Client/src/components/classSearch/reusable/sectionInfo/FormatPrereq.tsx
Client/src/components/seo/DefaultSEO.tsx
Client/src/components/splashPage/team/Team.tsx
Client/src/components/ui/reusable-dropdown.tsx
Client/src/pages/AboutPage.tsx
Client/src/pages/register/LoginForm.tsx
Client/src/pages/register/SignUpForm.tsx
package-lock.json
server/src/helpers/assistants/SectionQuery/sectionQuerySchema.ts

Fixed React DOM nesting warnings and improved the prerequisites display component by addressing invalid HTML structure and enhancing the UI consistency.
Closes #XXX (Replace with actual issue number)
- Fixed DOM nesting warnings by:
- Replacing `<p>` tag with `<div>` in `SectionDoc.tsx` to properly contain the `FormatPrerequisites` component
- Restructuring the prerequisites list to avoid invalid nesting of `<li>` elements
- Ensuring proper HTML hierarchy for headings and lists
- Enhanced the prerequisites display:
- Improved the advanced parsing section to use consistent styling with the non-advanced section
- Added `BadgeSection` components for better visual presentation of course codes
- Implemented proper spacing and alignment for OR conditions between courses
- Code quality …

Fixed console errors

---

Client/src/components/scheduleBuilder/aiChat/BuildScheduleAIChatContainer.tsx
Client/src/components/scheduleBuilder/aiChat/ChatContainerScheduleBuilder.tsx

enable auto scroll for scheduel builder chat

---

Client/src/components/scheduleBuilder/aiChat/BuildScheduleAIChatContainer.tsx
Client/src/components/scheduleBuilder/aiChat/ChatContainerScheduleBuilder.tsx

Merging latest updates from main into branch for consistency

enable auto scroll for scheduel builder chat (#344)

---

Client/src/components/scheduleBuilder/aiChat/AIChatLoadingMessage.tsx
Client/src/components/scheduleBuilder/aiChat/ChatContainerScheduleBuilder.tsx
Client/src/components/scheduleBuilder/aiChat/SBChatMessage.tsx
Client/src/components/scheduleBuilder/aiChat/ToolUsageDisplay.tsx
Client/src/components/scheduleBuilder/aiChat/TurnConversationItem.tsx
Client/src/redux/scheduleBuilderLog/scheduleBuilderLogSlice.ts
shared/src/types/scheduleBuilderLog/index.ts

Refactored tool call handling in the schedule builder to improve reliability and maintainability. Added a more direct thunk-based solution for processing tool calls. Added an improved loading display that shows tool usage in real-time.
Closes #
- Added a new `processToolCalls` thunk to handle tool calls directly
- Modified the `sendMessage` thunk to process tool calls immediately when received
- Added proper async handling for tool call processing
- Enhanced loading display with real-time tool usage feedback
1. **Real-Time Updates**
- Direct processing of tool calls when they arrive
2. **Better Reliability**
- Tool calls are processed immediately upon receipt
- No race conditions or timing issues
- Redux's built-in mechanisms handle deduplication
3. **Improved Maintainability**
- Simpler …

Improving streaming

---

Client/src/components/scheduleBuilder/aiChat/AIChatLoadingMessage.tsx
Client/src/components/scheduleBuilder/aiChat/ChatContainerScheduleBuilder.tsx
Client/src/components/scheduleBuilder/aiChat/SBChatMessage.tsx
Client/src/components/scheduleBuilder/aiChat/ToolUsageDisplay.tsx
Client/src/components/scheduleBuilder/aiChat/TurnConversationItem.tsx
Client/src/redux/scheduleBuilderLog/scheduleBuilderLogSlice.ts
shared/src/types/scheduleBuilderLog/index.ts

Merging new commit from main into branch for consistency

Improving streaming (#346)

---

Client/src/components/chat/chatBody/ChatLoadingMessage.tsx
Client/src/components/scheduleBuilder/aiChat/AIChatLoadingMessage.tsx
Client/src/components/scheduleBuilder/aiChat/SBChatMessage.tsx
Client/src/components/scheduleBuilder/aiChat/ToolUsageDisplay.tsx
server/src/helpers/assistants/scheduleBuilder/scheduleBuilderAgent.ts

Fixed a cross-browser compatibility issue with the loading message text visibility in the AI chat interface, specifically addressing text transparency issues in Chrome while maintaining the gradient animation effect.
Closes #
- Refactored the gradient text animation to only apply to the loading message text, not the tool usage display
- Moved the gradient styling from the container `motion.div` to a new `motion.span` component
- Improved dark mode compatibility by allowing `ToolUsageDisplay` to use its own text styling
- Fixed text visibility issues in Chrome while maintaining the same functionality in Firefox
Before (Chrome):
- Text was invisible due to transparency issues
- Tool usage messages were not visible
After:
- Loading message text has gradient animation
- Tool usage messages …

text streaming color visible in chrome browser

---

Client/src/components/scheduleBuilder/aiChat/ChatContainerScheduleBuilder.tsx

Improved the scroll behavior in the Schedule Builder chat to provide a better user experience when examining sections and tools at the bottom of messages. The changes make the scroll behavior more predictable and less intrusive, matching the behavior of the main chat container.
Closes #
- Simplified scroll behavior to match the main chat container's approach
- Removed complex idle detection and smooth scrolling logic
- Adjusted bottom threshold to 20 pixels for consistent behavior
- Implemented immediate scroll updates instead of animated scrolling
- Removed unnecessary timeouts and animation frames
- Improved scroll position detection for better user control
[No screenshots needed as this is a behavioral change]
The changes make the chat behavior more consistent with the main chat …

Auto scrolling stops when user scrolls up

---

Client/src/components/scheduleBuilder/aiChat/ChatContainerScheduleBuilder.tsx
Client/src/components/scheduleBuilder/aiChat/SBAssistantSuggestedMessages.tsx
Client/src/components/scheduleBuilder/aiChat/ScheduleBuilderAIChat.tsx
Client/src/components/ui/typewriter-effect.tsx

Implemented suggested questions for new chats and fixed auto-scrolling behavior in the schedule builder chat interface.
Closes # (you can add the issue number here)
- Added a new component `SBAssistantSuggestedMessages` for displaying suggested questions
- Implemented a responsive grid layout that shows two columns on larger screens and one column on smaller screens
- Added "Build schedule from flowchart" and "Summarize schedule" as initial suggested questions
- Integrated the component into the empty state of the chat container
- Fixed auto-scrolling behavior for the first message in chat
- Added `isFirstMessageRef` to properly track the first message state
- Improved scroll handling during message streaming
- Implemented proper scroll behavior that only auto-scrolls when:
- It's the …

auto scrolling fix

---

server/src/routes/scheduleBuilder.ts

This PR implements chat memory functionality in the Schedule Builder by preserving and utilizing previous assistant messages from the conversation history. This enhancement allows the AI to maintain context across multiple interactions, leading to more coherent and contextually aware responses.
Closes # [Add issue number if applicable]
- Added filtering of previous messages to only include non-empty assistant messages
- Implemented message history injection into the conversation state
- Modified the message initialization to include previous context
- Removed debug logging statements
- Added proper type handling for message content
1. **Message Filtering**
```typescript
const previousMessages = currentLog?.conversation_turns
.map((turn) => turn.messages)
.flat()
.filter(msg => msg.role …
```

Adding memory to ai chat

---

Client/src/components/ChatWidget/ChatWidget.tsx
Client/src/components/scheduleBuilder/aiChat/CurrentToolCall.tsx
Client/src/components/scheduleBuilder/aiChat/FormattedChatMessage.tsx
Client/src/components/scheduleBuilder/aiChat/SBAssistantSuggestedMessages.tsx
Client/src/components/scheduleBuilder/aiChat/SBChatMessage.tsx
Client/src/components/scheduleBuilder/aiChat/helpers/formattingStr.ts
Client/src/redux/scheduleBuilderLog/scheduleBuilderLogSlice.ts

Tool Calls and tool tip for assistant message

---

Client/src/components/ChatWidget/ChatWidget.tsx
Client/src/components/scheduleBuilder/aiChat/CurrentToolCall.tsx
Client/src/components/scheduleBuilder/aiChat/ScheduleBuilderAIChat.tsx
Client/src/components/scheduleBuilder/aiChat/ScheduleBuilderChatInput.tsx
Client/src/components/ui/placeholders-and-vanish-input.tsx
Client/src/redux/scheduleBuilderLog/scheduleBuilderLogSlice.ts

Refactor chat widget UI and enhance message streaming experience
Closes #
- Refactored ChatWidget component to improve UI/UX:
- Added new refs for chat input components
- Updated styling for better visual hierarchy
- Improved backdrop blur and border effects
- Adjusted minimum height and exit animations
- Enhanced CurrentToolCall component:
- Added state management for tooltip visibility
- Implemented pinning functionality for tooltips
- Added animation for streaming messages
- Improved scroll behavior and auto-scrolling
- Added click-away handling for unpinned tooltips
- Improved ScheduleBuilderChatInput:
- Replaced textarea with new PlaceholdersAndVanishInput component
- Added placeholder suggestions for common queries
- Enhanced input validation and error handling
- Improved loading …

Minimized chat widget

---

Client/src/components/scheduleBuilder/aiChat/SBChatMessage.tsx
Client/src/components/scheduleBuilder/aiChat/SBManageSchedule.tsx
Client/src/components/scheduleBuilder/aiChat/helpers/FormattingStrs.tsx
Client/src/components/ui/placeholders-and-vanish-input.tsx

This PR introduces several improvements to the Schedule Builder component, including enhanced course section parsing, draft message persistence, and UI refinements.
Closes #123 (Replace with actual issue number)
- Added `formattedCourses` property to `ManageScheduleArgs` interface
- Enhanced section parsing logic in `SBManageSchedule` component to handle both JSON and plain text formats
- Improved error handling for section parsing with fallback to class number extraction
- Removed development-only console logging for formatted courses
- Added draft message persistence in `PlaceholdersAndVanishInput` component
- Implemented automatic value synchronization with draft messages
- Enhanced input field focus management
- The enhanced section parsing now supports both structured JSON data and …

Schedule Builder UI and Functionality Updates

---

Client/src/components/scheduleBuilder/buildSchedule/ScheduleBuilderForm.tsx
Client/src/components/scheduleBuilder/buildSchedule/preferences/Preferences.tsx
Client/src/components/scheduleBuilder/buildSchedule/selectedSections/SectionsChosen.tsx
Client/src/redux/schedule/scheduleSlice.ts
Client/src/redux/scheduleBuilderLog/scheduleBuilderLogSlice.ts
Client/src/redux/sectionSelection/crudSelectionSection.ts
Client/src/redux/sectionSelection/sectionSelectionSlice.ts
server/src/helpers/assistants/scheduleBuilder/helpers.ts
server/src/helpers/assistants/scheduleBuilder/state.ts
server/src/helpers/assistants/scheduleBuilder/tools.ts
server/src/routes/scheduleBuilder.ts
server/src/routes/selectedSection.ts

Schedule builder bug fixes

---

Client/src/components/ChatWidget/ChatWidget.tsx
Client/src/components/classSearch/courseFilters/helpers/constants.ts
Client/src/components/scheduleBuilder/aiChat/ScheduleBuilderAIChat.tsx
Client/src/components/scheduleBuilder/aiChat/helpers/FormattingStrs.tsx
Client/src/components/scheduleBuilder/buildSchedule/preferences/Preferences.tsx
Client/src/components/ui/placeholders-and-vanish-input.tsx
Client/src/redux/schedule/scheduleSlice.ts
server/src/helpers/assistants/scheduleBuilder/scheduleBuilderAgent.ts
server/src/helpers/assistants/scheduleBuilder/state.ts
server/src/helpers/assistants/scheduleBuilder/tools.ts
shared/src/types/section/index.ts

This PR introduces several UI and functionality improvements across the application, focusing on chat widget styling, schedule builder preferences, and text formatting enhancements.
Closes #
- Updated ChatWidget styling with improved transparency and border colors
- Enhanced PlaceholdersAndVanishInput component with better border styling and focus states
- Adjusted chat container heights in ScheduleBuilderAIChat for better spacing
- Changed default behavior for time conflicts:
- Renamed `withNoConflicts` to `withTimeConflicts` for clarity
- Set default value to `true` across multiple components
- Updated initial filter values to reflect this change
- Improved message formatting in FormattingStrs.tsx:
- Added more descriptive default messages for empty states
- Enhanced readability of …

Style bug fixes

---

Client/src/redux/scheduleBuilderLog/crudScheduleBuilderLog.ts
Client/src/redux/sectionSelection/sectionSelectionSlice.ts
server/src/helpers/assistants/scheduleBuilder/state.ts
server/src/helpers/assistants/scheduleBuilder/tools.ts
server/src/routes/scheduleBuilder.ts

This PR implements several improvements to the schedule builder functionality, focusing on better state management, cleaner message handling, and more consistent schedule updates. The changes enhance the reliability of schedule modifications and improve the display format of section information.
Closes # (You'll need to add the specific issue number)
- Improved schedule state management in the `manageSchedule` tool
- Enhanced section information display format for better readability
- Removed redundant console logging
- Streamlined message handling in the schedule builder
- Implemented proper schedule persistence
- Added section summaries for better context
- Removed unused reducer case in section selection slice
- Improved error handling and state consistency
The changes focus on …

Other bug fixes

---

Client/src/components/scheduleBuilder/aiChat/SBChatMessage.tsx
Client/src/components/scheduleBuilder/aiChat/ToolUsageDisplay.tsx
Client/src/components/scheduleBuilder/aiChat/helpers/FormattingStrs.tsx
server/src/helpers/assistants/scheduleBuilder/helpers.ts
server/src/helpers/assistants/scheduleBuilder/state.ts
server/src/helpers/assistants/scheduleBuilder/tools.ts
server/src/index.ts
server/src/routes/test.ts

This PR replaces the "user_selected" fetch type with "alternate" fetch type in the schedule builder functionality, improving the way alternate sections are fetched and displayed for courses. The changes enhance the user experience by providing better organization and clarity when viewing alternative section options.
Closes #XXX (Please add the relevant issue number)
- Replaced `user_selected` fetch type with `alternate` fetch type across the codebase
- Added new `course_ids` parameter to support fetching alternate sections for specific courses
- Implemented new `getAlternateSections` helper function to fetch and sort alternate sections
- Updated UI components to display alternate sections with improved formatting
1. **Type Definitions**
- Updated `FetchSectionsArgs` interface to use …

Adding alternate sections

---

Client/src/components/splashPage/team/Contributors.tsx
Client/src/components/splashPage/team/PersonCard.tsx
Client/src/components/splashPage/team/Team.tsx
shared/src/types/team/index.ts

Team Page Modifications

---

.github/workflows/ci.yml
package-lock.json
server/jest.config.ts
server/package.json
server/src/__tests__/helpers/testUtils.ts
server/src/__tests__/routes/auth.test.ts
server/src/__tests__/setup.ts
server/src/index.ts

Setting up Unit Testing with Jest on Server

---

Client/src/components/chat/chatBody/AssistantSuggestedMessages.tsx
Client/src/components/chat/chatBody/ChatContainer.tsx
Client/src/components/chat/chatBody/ChatLoadingMessage.tsx
Client/src/components/chat/chatBody/ChatMessage.tsx
Client/src/components/chat/chatBody/MobileChatContainer.tsx
Client/src/components/chat/chatBody/README.md
Client/src/components/chat/chatFooter/ChatInput.tsx
Client/src/components/chat/chatFooter/README.md
Client/src/components/chat/chatHeader/ModeDropDown.tsx
Client/src/components/chat/chatHeader/NewChat.tsx
Client/src/components/chat/chatHeader/README.md
Client/src/components/chat/chatSideBar/AssistantItem.tsx
Client/src/components/chat/chatSideBar/AssistantSelector.tsx
Client/src/components/chat/chatSideBar/README.md
Client/src/components/chat/helpers/README.md
Client/src/components/chat/helpers/formatHelper.ts
Client/src/components/chat/helpers/handleModeSelection.ts
Client/src/components/chat/helpers/newChatHandler.ts
Client/src/components/chatLog/ChatLog.tsx
Client/src/components/chatLog/ChatLogList.tsx
Client/src/components/chatLog/ChatLogOptions.tsx
Client/src/components/chatLog/README.md
Client/src/components/chatWidget/ChatWidget.tsx
Client/src/components/chatWidget/README.md
Client/src/pages/ScheduleBuilder.tsx

1. **Component Documentation Structure**
- Each component now has detailed JSDoc-style documentation at the top
- Documentation includes:
- Component description
- Props and their types
- Features and capabilities
- Dependencies
- Behavior and implementation details
- Related components and Redux connections
2. **New README Files**
Several new README files have been added to document different sections of the chat interface:
a) **Chat Body Components** (`chatBody/README.md`)
- Documents core components like `ChatContainer`, `MobileChatContainer`, `ChatMessage`, etc.
- Explains state management, key features, and component interactions
- Details technical considerations and future improvements
b) **Chat Footer Components** (`chatFooter/README.md`)
- Focuses on the `ChatInput` component
- …

Creating docs
