Client/src/components/chatLog/ChatLog.tsx, Client/src/components/chatLog/deleteLog/DeleteLog.module.css, Client/src/components/chatLog/deleteLog/DeleteLog.tsx, Client/src/components/customGPT/ModeDropDown.tsx, Client/src/redux/log/logSlice.ts, Client/src/redux/message/messageSlice.ts, Client/src/types/log/logTypes.ts
- Previous Problem where users could repeatedly submit multiple delete requests for a chatlog, while the initial request was still `pending` leading to the other requests getting a 404 error 
- **Solution**: Ensured that logs being currently deleted were in an array. Before deleting a log, we check to see if their logId is present in this array, so we don't duplicate the same request. 
- If a user clicks outside the ModeDropdown Menu, it closes the menu providing a better experience for the user
- Small TS changes now that we are using uuid for the messageIds which is a string
=> UI Bug Fixes

Client/src/components/chat/ChatMessage.tsx, Client/src/hooks/useTrackAnalytics.ts, Client/src/redux/message/crudMessage.ts, Client/src/redux/message/messageSlice.ts, Client/src/types/message/messageType.ts, server/db/models/analytics/messageAnalytics/messageAnalyticsCollection.js, server/db/models/analytics/messageAnalytics/messageAnalyticsServices.js, server/db/models/chatlog/chatLogCollection.js, server/db/models/chatlog/chatLogServices.js, server/routes/analytics/messageAnalytics.js, server/routes/chatLog.js
- Users were able to submit their rating on a bot's message and it was successfully being saved in our analytics table
- Front-end also managed state for this and had a green thumbs or a red thumbs down. 
- However, we were not saving the userReaction in the ChatLogs collection, so this state for each bot message was not able to save on the frontend.
- Add a new property to the message object `userReaction`
- This will also get saved in our MongoDB collection
=> UserReaction being tracked in the Message Object 

Client/src/components/ui/file-upload.tsx, Client/src/redux/message/crudMessage.ts, Client/src/redux/message/messageSlice.ts, server/helpers/azure/blobFunctions.js, server/routes/llm.js
- If a PDF is received that is greater than `1MB`, send an error message back with status code `413` to notify the user that file sizes must be less than `1MB`
- If the file size is greater than `1MB` immediately set the file to `null` and add a user message
- Error message disappears if the file changes and is less than 1MB or if the user submits a message.
- The server side should never receive a file pdf that is bigger than `1MB` due to how the client does not allow this. However, just in case, it is still implemented to cover all cases.
=> PDF File Size Error Handling

Client/src/components/chat/ChatInput.tsx, Client/src/components/chat/ChatMessage.tsx, Client/src/components/ui/skeleton.tsx, Client/src/redux/message/crudMessage.ts, Client/src/redux/message/messageSlice.ts, Client/src/types/message/messageType.ts, server/routes/chatLog.js
- Previously, when a user sent a message we would not update the UI to display this message until the response started streaming back to us
- This was not an ideal design, so the plan was to display the user's message immediately on the UI as soon as they submit the message. Also display a bot message placeholder to show that the message is loading
- Add a new optional property to the bot message object called `thinkingState`
- When set to true, the user has submitted their message but the response is not streaming out yet
- The order of dispatching events was also changed to dispatch the actions of user and bot message before we send the request to stream it.
- Use this custom component [Skeleton](https://ui.shadcn.com/docs/components/skeleton) to display the bot's message thinking state
=> Frontend loading message UI

Client/src/components/layout/ChatPage/ChatPageSidebar.tsx, Client/src/index.css
Bug where ChatLogs options was not visible 
This was caused when using the `@radix-ui/react-scroll-area component` and  automatically applying display: table to an inner div.
The simplest approach was to override with CSS 
```css
[data-radix-scroll-area-viewport] > div {
display: block !important;
}
```
=> ChatLog Options Not Visible

Client/package.json, Client/src/components/chat/ChatInput.tsx, Client/src/components/chat/NewChat.tsx, Client/src/components/chat/helpers/newChatHandler.ts, Client/src/components/layout/ChatPage/ChatPageHeader.tsx, Client/src/pages/ChatPage.tsx, Client/src/redux/log/logSlice.ts, server/src/db/models/chatlog/chatLogCollection.ts, server/src/helpers/assistants/multiAgent.ts, server/src/routes/chatLog.ts, shared/src/types/log/index.ts
- Previously, our application allowed users to use the same chatlog and switch around multiple assistants
- To make things less complicated for the thread, I decided to tie the assistant with the chatlog
- Assistant Ids are now stored with the chat log
- Selecting a new assistant makes a new chat
- Selecting a Chat Log updates assistant to the chat log's assistantMongoId
- In the previous commit, I removed the feature for files
- We can still implement this for specific assistants but did not see a need for it as of right now.
- In the threads collection I will add the assistantMongoId and make vectorStoreId optional and only necessary if the student is using an assistant that allows for file uploads.
=> ChatLogs are mapped to their respective assistant

server/src/db/models/threads/threadCollection.ts, server/src/db/models/threads/threadServices.ts, server/src/helpers/assistants/multiAgent.ts, server/src/helpers/assistants/singleAgent.ts, server/src/helpers/openAI/threadFunctions.ts, shared/src/types/thread/index.ts
```typescript
export type ThreadData = {
threadId: string;
vectorStoreId: string | null;
assistantId?: string; // TO-DO: Eventually make this required (only optional for now for backwards compatibility)
};
export type ThreadDocument = ThreadData & {
_id: string;
};
```
- vectorStoreId is `null` if the assistant does not allow for matching, then the vectorStoreId is null
- This also prevents vectorStoreIds from being created using openAI API
- Added `assistantId`
- Currently optional but will make it mandatory once I refresh the database with a clean slate before deployment
=> New ThreadData Type

server/src/routes/llm.ts
- Fixed the bug where a user tries to cancel a completed run.
- Was a small edge case
=> Bug Fix: Cancelling a Completed Run

Client/src/components/chat/ChatContainer.tsx, Client/src/components/chat/ChatInput.tsx, Client/src/components/chat/NewChat.tsx, Client/src/components/chat/helpers/newChatHandler.ts, Client/src/components/chatLog/ChatLogOptions.tsx, Client/src/components/layout/ChatPage/ChatPageHeader.tsx, Client/src/components/layout/ChatPage/ChatPageSidebar.tsx, Client/src/pages/ChatPage.tsx, Client/src/redux/log/logSlice.ts, Client/src/redux/message/messageSlice.ts, server/src/routes/chatLog.ts, server/src/routes/llm.ts, shared/src/types/message/index.ts
- Previously, I had a redux state for the `msgList` which is all the messages of the chat log stored in state 
- I am changing this approach because there was a bug I caught
- The bug occurred because I was updating the chatLog's content and setting it to our msgList
- However, the msgList depended on our current chatLog shown given the id from the url
- The case where this caused a bug is when a message was being streamed out and the user clicked onto another chatLog or made a new chat 
- This is an edge case, but the results would mean that the previous chat log that was clicked off would have its entire content erased and replaced
- The solution was to `normalize` the chatId
- What i mean by this is storing fetched chatIds in state 
- I also am now keeping track of loading chatIds that …
=> # MessageList Approach

Client/src/components/flowchart/flowchartLog/FlowchartLogOptions.tsx
FLOWCHART:
previously, if we tried to rename a chat log and pressed save, the popover wouldn't actually disappear
same logic as chat page
=> added state to handle renaming

Client/src/components/section/SectionDoc.tsx
searching now defaults to closed so user has to press "expand"
"collapse all" changed to "expand"
no ratings increased size to match all the other sections
=> changed styling on class search page

Client/src/components/calendar/buildSchedule/selectedSections/SectionsChosen.tsx, Client/tailwind.config.js
- Changed overall weekly calendar UI to match figma design
- Moved remove button down
- Start and End time changed to Time
- Added type of section (Lec/Lab)
=> Refactored Weekly calendar UI

Client/src/components/calendar/buildSchedule/layout/MobileBuildScheduleContainer.tsx, Client/src/components/layout/SectionPage/MobileSectionPageLayout.tsx, Client/src/components/section/courseFilters/SectionForm.tsx, Client/src/hooks/useDeviceType.ts, Client/src/index.css, Client/src/pages/SectionPage.tsx, Client/tailwind.config.js
- Modified the mobile layout for sections so that the `Apply Filters` button is no longer hidden
- Closes #213 
- I created a new custom hook to determine what device the user is on
- For mobile/tablet devices we will display a new layout for the section page
-
- As of right now, the naming convention of the components is a little confusing. As we have the `isMobile` hook which only checks the screen width.
- I will change this soon so that the naming makes more sense
=> Added new layout for mobile devices section page

Client/src/components/layout/MobileHeader.tsx
Synchronized chat navigation logic between mobile header and sidebar components to ensure consistent assistant selection behavior across all screen sizes.
Closes #233 
- Added Redux dispatch and selector hooks to MobileHeader component
- Implemented `handleChatClick` function in MobileHeader to match OuterSidebar logic
- Added necessary imports for Redux actions and chat helper functions
- Updated chat navigation in MobileHeader to properly set initial state and default assistant
- Ensured consistent behavior for assistant selection across all screen sizes
This change ensures that the Cal Poly SLO Assistant (first assistant in the list) is always selected by default when navigating to the chat interface, regardless of screen size or navigation method. The fix maintains existing …
=> [Bug-Mobile-Chat-Navigation]: Fix Chat Navigation for Small Width Devices

Client/src/components/calendar/weeklyCalendar/layout/CalendarContainer.tsx, Client/src/components/chat/chatBody/ChatMessage.tsx, Client/src/components/flowchart/flowchartSidebar/SidebarFlowchart.tsx, Client/src/components/flowchart/layout/FlowchartUnitCounts.tsx, Client/src/components/layout/CalendarPage/CalendarPageLayout.tsx, Client/src/components/layout/ChatPage/ChatPageSidebar.tsx, Client/src/components/layout/FlowchartPage/FlowchartLayout.tsx, Client/src/components/layout/ProfilePage/ProfilePageLayout.tsx, Client/src/components/layout/SectionPage/SectionPageLayout.tsx, Client/src/components/layout/splashPage/SplashHeader.tsx, Client/src/components/register/SignInFlow/index.tsx, Client/src/components/register/TitleCard.tsx, Client/src/components/section/layout/SectionContainer.tsx, Client/src/components/ui/sidebar.tsx, Client/src/hooks/useIsNarrowScreen.ts, Client/src/pages/CalendarPage.tsx, Client/src/pages/ChatPage.tsx, Client/src/pages/FlowchartPage.tsx, Client/src/pages/SectionPage.tsx, Client/src/pages/register/Register.tsx
Refactoring mobile detection hook
Closes #218 
- Refactored the `useIsMobile` hook to `useIsNarrowScreen`. Functionality still remains the same, and this just a renaming of all variables relating to the mobile hook across the entire codebase.
- [ ✅ ] My code follows the **PolyLink Contribution Guidelines**.
- [ ✅ ] I have **tested my changes** to ensure they work as expected.
- [ ✅ ] I have **documented my changes** (if applicable).
- [ ✅ ] My PR has **a clear title and description**.
N/A
=> Refactor mobile detection hook: replace use-mobile with useIsNarrowScreen across components

Client/src/components/calendar/buildSchedule/CalendarBuilderForm.tsx, Client/src/components/calendar/buildSchedule/preferences/Preferences.tsx, Client/src/redux/calendar/calendarSlice.ts
- minor frontend changes for schedule/calendar builder page
N/A
- Edited `CalendarBuilderForm.tsx` to have "New Schedule" button be "Generate Schedule"
- Updated default value for "Only Open Classes" button to false in `calendarSlice.ts` and `buildschedule/preferences/Preferences.tsx`
- [ ✅] My code follows the **PolyLink Contribution Guidelines**.
- [ ✅] I have **tested my changes** to ensure they work as expected.
- [ ✅] I have **documented my changes** (if applicable).
- [ ✅] My PR has **a clear title and description**.
N/A
=> Update schedule generation button text and adjust default preferences

Client/src/components/calendar/buildSchedule/savedSchedules/CalendarOptions.tsx, server/src/db/models/calendar/calendarListCollection.ts
- Fixing a bug for users that were not able to save their schedules 
- 
Closes #
- If a calendar collection is not found, we return a default template. This is was the root cause of the error as no collection was being created and therefore a user could not save their schedule  (server side bug)
- Also fixed an issue where a user would update their non primary schedule and the primary schedule would be lost. This was a client side bug where we were returning false when we should have been returning the primary calendar id
-
=> Save Calendar bug fix

Client/src/components/chat/chatBody/ChatMessage.tsx, Client/src/components/classSearch/layout/SectionContainer.tsx, Client/tsconfig.json
- Fixed bug where page would crash because we were importing a library incorrectly as a constructor
- 
Closes #
- Updated TypeScript configuration to enable esModuleInterop
-
-
=> Bug Fix Page Crash for Import

server/src/db/models/schedule/transformSection.ts, server/src/db/models/selectedSection/selectedSectionServices.ts, shared/package.json, shared/src/constants/colors/index.ts, shared/src/constants/index.ts
This PR addresses two important improvements: (1) enhancing color consistency for sections with the same courseId in the schedule transformation process, and (2) fixing module import issues with the `@polylink/shared` package. These changes improve both the user experience and developer experience.
Closes #
- Modified the `transformClassNumbersToSelectedSections` function to maintain color consistency by courseId
- Added a `courseIdToColorMap` to track and assign colors based on courseId rather than classNumber
- Implemented a two-pass approach:
- First pass: Identify and map colors to courseIds
- Second pass: Apply the mapped colors to each section
- Enhanced color lookup logic to:
- First check if the current classNumber has a color
- Then look for any classNumber with the same courseId …
=> New color folder in shared package

Client/src/components/classSearch/reusable/sectionInfo/StarRating.tsx, Client/src/components/scheduleBuilder/weeklySchedule/ScheduleAverageRating.tsx, Client/src/components/scheduleBuilder/weeklySchedule/WeeklySchedule.tsx
This PR improves the responsiveness of the star rating components for narrow screen views. It reduces the size of stars and adjusts text sizes to better utilize space without increasing the component's height.
Closes #N/A
- Added `isNarrowScreen` prop to the `StarRating` and `Star` components to conditionally render different sizes based on screen width
- Reduced star size on narrow screens from 18px to 14px
- Decreased SVG dimensions on narrow screens from 16px to 12px
- Reduced margin between stars on narrow screens from 2px to 1px
- Made text sizes responsive with smaller sizes on narrow screens
- Improved layout with column layout on small screens and row layout on larger screens
- Added truncation to the title to prevent overflow on narrow screens
- Decreased spacing between elements …
=> Improve the dynamic styling for weekly schedule

Client/src/components/classSearch/courseFilters/courseInformation/CourseInformation.tsx, Client/src/components/classSearch/courseFilters/helpers/api/subjects.ts, Client/src/components/classSearch/courseFilters/instructorAndRatings/Instructor.tsx, Client/src/components/classSearch/reusable/filter/SearchBar.tsx
Added a "No Subject" option to the subject dropdown to allow users to easily clear their subject selection without resetting all filters.
Closes #[issue number]
- Added a "No Subject" option to the `SUBJECTS` constant in `subjects.ts` with:
- `subject: "none"` as the value
- `description: "No Subject"` as the label
- Placed at the top of the list for easy access
- Modified the subject dropdown in `CourseInformation.tsx` to:
- Handle the special "none" value in the `handleChangeItem` function
- Convert "none" to an empty string when setting the form value
- Properly display the selected item based on the field value
[Add a screenshot showing the subject dropdown with the "No Subject" option]
This change improves the user experience by providing a clear way to remove the subject filter …
=> Filtering bugs fixed

Client/src/components/classSearch/courseFilters/SectionForm.tsx, Client/src/components/classSearch/courseFilters/helpers/constants.ts, Client/src/components/classSearch/courseFilters/scheduling/Scheduling.tsx, Client/src/redux/classSearch/classSearchSlice.ts
=> Reset Filtering Bug fix

Client/src/components/classSearch/courseFilters/helpers/constants.ts, Client/src/components/classSearch/courseFilters/scheduling/Scheduling.tsx, server/src/db/models/section/sectionServices.ts
Updated the backend section query builder to properly handle instruction mode filtering based on the single code selection in the frontend form.
Closes #
- Updated the instruction mode filtering logic in `server/src/db/models/section/sectionServices.ts` to handle single code selection from the frontend
- Modified the switch statement to correctly map each instruction mode code to its corresponding database value
- Ensured the backend filtering logic matches the frontend UI options:
- "PS" - In-Person
- "SA" - Asynchronous
- "PA" - Synchronous
- "P" - In-Person/Async Hybrid
- "AM" - In-Person/Sync Hybrid
- "SM" - Sync/Async Hybrid
The changes ensure that when a user selects an instruction mode option in the frontend form, the backend correctly filters sections based on that selection. This …
=> Filter based on instruction mode

Client/src/components/scheduleBuilder/buildSchedule/selectedSections/SectionsChosen.tsx, Client/src/components/scheduleBuilder/weeklySchedule/ScheduleTimeSlots.tsx, Client/src/components/scheduleBuilder/weeklySchedule/WeeklySchedule.tsx, Client/src/redux/schedule/scheduleSlice.ts
This PR adds the ability for users to hide sections from their schedule view, providing more control over their schedule visualization. Users can toggle section visibility using an eye icon in both the schedule view and the sections list.
Closes #
- Added `hiddenSections` state to the Redux store to track which sections are hidden
- Implemented `toggleHiddenSection` reducer to handle showing/hiding sections
- Added eye icon to `ScheduleTimeSlots` component for toggling section visibility in the calendar view
- Added eye icon to `SectionsChosen` component for toggling section visibility in the sections list
- Eye icon only appears for sections that are part of the current generated schedule
- Hidden sections are visually indicated with reduced opacity
- Hidden sections are filtered out …
=> Weekly schedule visibile sections

Client/src/components/scheduleBuilder/buildSchedule/ScheduleBuilderForm.tsx
This PR modifies the schedule saving functionality to exclude hidden sections when saving a schedule, ensuring that only visible sections are persisted.
Closes #
- Modified `handleSaveSchedule` function to filter out hidden sections before saving
- Added `hiddenSections` to the state selector in `ScheduleBuilderForm`
- Only visible sections (not in the `hiddenSections` array) are now included in the saved schedule
- This change ensures that the saved schedule matches what the user is actually seeing in their current view
- Hidden sections are completely excluded from the saved schedule, not just hidden in the view
- This better reflects user intent since they've explicitly chosen to hide certain sections
- The change maintains consistency between what users see and what gets saved
=> Saving calendar based on visible sections

Client/src/components/classSearch/TermSelector.tsx, Client/src/components/classSearch/courseFilters/SectionForm.tsx, Client/src/components/classSearch/courseFilters/helpers/constants.ts, Client/src/components/scheduleBuilder/weeklySchedule/ScheduleAverageRating.tsx, Client/src/pages/ScheduleBuilder.tsx, server/src/db/models/section/fallSectionCollection.ts, server/src/db/models/section/sectionServices.ts, server/src/db/models/selectedSection/selectedSectionCollection.ts, server/src/routes/classSearch.ts, server/src/routes/llm.ts, server/src/routes/schedule.ts, server/src/types/express/index.d.ts, shared/src/types/section/index.ts, shared/src/types/selectedSection/index.ts
Added support for Fall 2025 term sections to the schedule builder, including UI components, API endpoints, and data handling. This update allows users to view and manage their Fall 2025 course schedules alongside existing Spring 2025 and Summer 2025 terms.
Closes # (Please add the relevant issue number)
- Added "fall2025" to the `VALID_TERMS` constant in `server/src/routes/schedule.ts`
- Updated the schedule builder UI to include Fall 2025 tab in both desktop and mobile views
- Added Fall 2025 term handling in the section filters form
- Implemented Fall 2025 term support in the class search API endpoints
- Added Fall 2025 term validation in the schedule creation and update endpoints
- Updated the schedule builder page layout to handle Fall 2025 term selection
- Added Fall 2025 term …
=> Fall2025 sections insertted

Client/src/components/scheduleBuilder/weeklySchedule/WeeklySchedule.tsx, Client/src/index.css
Improved the calendar time slot styling to handle overflow and font scaling in small time slots, ensuring better readability and consistent appearance across different slot sizes.
Closes #XXX (Please add the relevant issue number)
- Added responsive font sizing for calendar events using CSS custom properties and calc()
- Implemented proper overflow handling for time slots to prevent content from spilling out
- Added flexbox-based centering for event content within slots
- Optimized text display with ellipsis for overflow content
- Added specific FullCalendar class targeting for better event content control
- Implemented dynamic font scaling based on time slot height:
- Minimum font size: 8px
- Maximum font size: 16px
- Dynamic scaling: 30% of container height
- Added proper line height …
=> [Weekly Calendar Style Bug] Small time slots stylistic bug fix

Client/src/components/scheduleBuilder/buildSchedule/selectedSections/SectionsChosen.tsx, Client/src/components/scheduleBuilder/buildSchedule/selectedSections/SelectedSectionContainer.tsx, Client/src/redux/schedule/scheduleSlice.ts, server/src/db/models/schedule/transformSection.ts, shared/src/types/selectedSection/index.ts
Added term validation and user-friendly toast notifications when attempting to add sections from different terms to the schedule. This prevents accidental addition of sections from incorrect terms and provides a convenient way to switch terms.
Closes #
- Added term validation check in `handleAddToCalendar` function to prevent adding sections from different terms
- Implemented toast notification with:
- Clear error message showing course ID and class number
- Description explaining the term mismatch
- "Switch Term" action button for quick term switching
- Added early return when term mismatch is detected to prevent invalid section additions
- Integrated `useToast` hook in `SectionCard` component for toast functionality
N/A - Backend logic changes only
This change improves the user …
=> Schedule builder form 

Client/src/redux/scheduleBuilderLog/crudScheduleBuilderLog.ts, Client/src/redux/scheduleBuilderLog/scheduleBuilderLogSlice.ts, server/src/helpers/assistants/SectionQuery/sectionQueryAssistant.ts, server/src/helpers/assistants/scheduleBuilder/scheduleBuilderAgent.ts, server/src/helpers/assistants/scheduleBuilder/tools.ts, server/src/routes/scheduleBuilder.ts, shared/src/types/scheduleBuilderLog/index.ts
Improved the handling of tool call streaming in the schedule builder to prevent duplicate entries and better handle both streaming chunks and complete tool calls.
Closes # [Add issue number if applicable]
- Added `tool_call_chunks` property to `ScheduleBuilderMessage` type to properly handle streaming chunks
- Modified `receivedToolCalls` action to prevent duplicate tool calls by:
- Tracking existing tool call IDs using a Set
- Only adding new tool calls that don't already exist
- Handling both streaming chunks and complete tool calls separately
- Improved null handling and array initialization for safer operations
- Enhanced the streaming logic to:
- Handle partial JSON chunks during streaming
- Properly parse complete tool call objects
- Maintain streaming chunks until a complete object …
=> Streaming enhancement

Client/src/components/classSearch/courseFilters/helpers/constants.ts, Client/src/components/scheduleBuilder/aiChat/ScheduleBuilderChatInput.tsx, Client/src/components/scheduleBuilder/buildSchedule/preferences/Preferences.tsx, Client/src/components/scheduleBuilder/helpers/buildSchedule.ts, Client/src/redux/schedule/scheduleSlice.ts, server/src/helpers/assistants/scheduleBuilder/state.ts, server/src/routes/scheduleBuilder.ts, shared/src/types/scheduleBuilderLog/index.ts
=> Adding preferences

Client/src/components/ChatWidget/ChatWidget.tsx, Client/src/components/scheduleBuilder/aiChat/CurrentToolCall.tsx
Added minimized state handling to the CurrentToolCall component to properly handle widget minimization behavior.
Closes #XXX
- Added `minimized` prop to `CurrentToolCall` component
- Implemented automatic closing of tooltip when widget is minimized
- Added cleanup of pinned and forceMount states on minimization
- Updated `forceMount` behavior to consider minimized state
- Modified `ChatWidget` to pass minimized state to `CurrentToolCall`
N/A
This change improves the user experience by ensuring that tooltips and tool calls are properly cleaned up when the chat widget is minimized. The implementation maintains the existing functionality while adding proper state management for the minimized state.
=> fixed tooltip content render bug

Client/src/components/scheduleBuilder/aiChat/ScheduleBuilderChatInput.tsx, pr.md, server/src/helpers/assistants/scheduleBuilder/helpers.ts, server/src/helpers/assistants/scheduleBuilder/tools.ts, server/src/routes/scheduleBuilder.ts
This PR fixes a critical bug where AI-generated schedule updates were not being saved for new schedules that hadn't been stored in the database yet. The changes ensure that all schedule updates, whether for existing or new schedules, are properly persisted.
Closes #XXX
- Removed unused imports and functions to clean up the codebase
- Added proper handling of schedule updates for new schedules by:
- Transforming class numbers to selected sections before updating
- Ensuring new schedules are properly initialized with the correct structure
- Maintaining custom events when updating schedules
- Fixed the bug where AI updates weren't being saved for new schedules by properly handling the schedule update flow
This fix was critical for ensuring a consistent user experience when using the AI …
=> schedule now updated and stored in db

Client/src/components/scheduleBuilder/buildSchedule/timeConflicts/TimeConflictsPopup.tsx, Client/src/components/scheduleBuilder/helpers/filterScheduleList.ts, Client/src/helpers/transformSection.ts, Client/src/redux/classSearch/classSearchSlice.ts
=> Auto resolve conflicts
